// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module StreamingMaxPool_Batch_1_StreamingMaxPool_128u_2u_64u_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in0_V_TDATA,
        in0_V_TVALID,
        in0_V_TREADY,
        out_V_TDATA,
        out_V_TVALID,
        out_V_TREADY
);

parameter    ap_ST_fsm_state1 = 39'd1;
parameter    ap_ST_fsm_state2 = 39'd2;
parameter    ap_ST_fsm_state3 = 39'd4;
parameter    ap_ST_fsm_state4 = 39'd8;
parameter    ap_ST_fsm_state5 = 39'd16;
parameter    ap_ST_fsm_state6 = 39'd32;
parameter    ap_ST_fsm_state7 = 39'd64;
parameter    ap_ST_fsm_state8 = 39'd128;
parameter    ap_ST_fsm_state9 = 39'd256;
parameter    ap_ST_fsm_state10 = 39'd512;
parameter    ap_ST_fsm_state11 = 39'd1024;
parameter    ap_ST_fsm_state12 = 39'd2048;
parameter    ap_ST_fsm_state13 = 39'd4096;
parameter    ap_ST_fsm_state14 = 39'd8192;
parameter    ap_ST_fsm_state15 = 39'd16384;
parameter    ap_ST_fsm_state16 = 39'd32768;
parameter    ap_ST_fsm_state17 = 39'd65536;
parameter    ap_ST_fsm_state18 = 39'd131072;
parameter    ap_ST_fsm_state19 = 39'd262144;
parameter    ap_ST_fsm_state20 = 39'd524288;
parameter    ap_ST_fsm_state21 = 39'd1048576;
parameter    ap_ST_fsm_state22 = 39'd2097152;
parameter    ap_ST_fsm_state23 = 39'd4194304;
parameter    ap_ST_fsm_state24 = 39'd8388608;
parameter    ap_ST_fsm_state25 = 39'd16777216;
parameter    ap_ST_fsm_state26 = 39'd33554432;
parameter    ap_ST_fsm_state27 = 39'd67108864;
parameter    ap_ST_fsm_state28 = 39'd134217728;
parameter    ap_ST_fsm_state29 = 39'd268435456;
parameter    ap_ST_fsm_state30 = 39'd536870912;
parameter    ap_ST_fsm_state31 = 39'd1073741824;
parameter    ap_ST_fsm_state32 = 39'd2147483648;
parameter    ap_ST_fsm_state33 = 39'd4294967296;
parameter    ap_ST_fsm_state34 = 39'd8589934592;
parameter    ap_ST_fsm_state35 = 39'd17179869184;
parameter    ap_ST_fsm_state36 = 39'd34359738368;
parameter    ap_ST_fsm_pp1_stage0 = 39'd68719476736;
parameter    ap_ST_fsm_state39 = 39'd137438953472;
parameter    ap_ST_fsm_state40 = 39'd274877906944;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] in0_V_TDATA;
input   in0_V_TVALID;
output   in0_V_TREADY;
output  [63:0] out_V_TDATA;
output   out_V_TVALID;
input   out_V_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in0_V_TREADY;
reg out_V_TVALID;

(* fsm_encoding = "none" *) reg   [38:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    in0_V_TDATA_blk_n;
wire    ap_CS_fsm_state34;
wire   [0:0] icmp_ln78_fu_797_p2;
wire    ap_CS_fsm_state35;
reg    out_V_TDATA_blk_n;
wire    ap_CS_fsm_pp1_stage0;
reg    ap_enable_reg_pp1_iter1;
wire    ap_block_pp1_stage0;
reg   [0:0] icmp_ln89_reg_899;
reg   [6:0] outpix_reg_768;
wire   [6:0] yp_1_fu_779_p2;
reg   [6:0] yp_1_reg_856;
wire    ap_CS_fsm_state33;
wire   [0:0] icmp_ln77_fu_785_p2;
wire   [7:0] add_ln78_fu_791_p2;
reg   [7:0] add_ln78_reg_865;
reg    ap_block_state34;
wire   [6:0] select_ln78_fu_809_p3;
reg   [6:0] select_ln78_reg_873;
reg   [63:0] in0_V_read_reg_878;
reg   [5:0] buf_V_addr_65_reg_883;
wire   [6:0] add_ln79_fu_834_p2;
wire   [6:0] add_ln89_fu_839_p2;
reg    ap_enable_reg_pp1_iter0;
wire    ap_block_state37_pp1_stage0_iter0;
reg    ap_block_state38_pp1_stage0_iter1;
reg    ap_block_state38_io;
reg    ap_block_pp1_stage0_11001;
wire   [0:0] icmp_ln89_fu_845_p2;
wire    ap_CS_fsm_state36;
reg    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state37;
reg   [5:0] buf_V_address0;
reg    buf_V_ce0;
reg    buf_V_we0;
wire   [63:0] buf_V_q0;
reg   [5:0] buf_V_address1;
reg    buf_V_ce1;
reg    buf_V_we1;
reg   [63:0] buf_V_d1;
reg   [6:0] yp_reg_735;
wire    ap_CS_fsm_state32;
wire    ap_CS_fsm_state39;
reg   [7:0] indvar_flatten_reg_746;
reg   [6:0] xp_reg_757;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state22;
wire    ap_CS_fsm_state23;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state25;
wire    ap_CS_fsm_state26;
wire    ap_CS_fsm_state27;
wire    ap_CS_fsm_state28;
wire    ap_CS_fsm_state29;
wire    ap_CS_fsm_state30;
wire    ap_CS_fsm_state31;
wire   [63:0] zext_ln79_fu_817_p1;
wire   [63:0] zext_ln89_fu_851_p1;
reg    ap_block_pp1_stage0_01001;
wire   [63:0] or_ln709_fu_827_p2;
wire   [0:0] icmp_ln79_fu_803_p2;
wire   [63:0] or_ln709_1_fu_822_p2;
wire    ap_CS_fsm_state40;
reg   [38:0] ap_NS_fsm;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 39'd1;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
end

StreamingMaxPool_Batch_1_StreamingMaxPool_128u_2u_64u_s_buf_V #(
    .DataWidth( 64 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
buf_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_V_address0),
    .ce0(buf_V_ce0),
    .we0(buf_V_we0),
    .d0(64'd0),
    .q0(buf_V_q0),
    .address1(buf_V_address1),
    .ce1(buf_V_ce1),
    .we1(buf_V_we1),
    .d1(buf_V_d1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b1 == ap_condition_pp1_exit_iter0_state37))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state36)) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state37))) begin
            ap_enable_reg_pp1_iter1 <= (1'b1 ^ ap_condition_pp1_exit_iter0_state37);
        end else if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end else if ((1'b1 == ap_CS_fsm_state36)) begin
            ap_enable_reg_pp1_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((in0_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state35))) begin
        indvar_flatten_reg_746 <= add_ln78_reg_865;
    end else if (((1'b1 == ap_CS_fsm_state33) & (icmp_ln77_fu_785_p2 == 1'd0))) begin
        indvar_flatten_reg_746 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        outpix_reg_768 <= 7'd0;
    end else if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln89_fu_845_p2 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        outpix_reg_768 <= add_ln89_fu_839_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((in0_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state35))) begin
        xp_reg_757 <= add_ln79_fu_834_p2;
    end else if (((1'b1 == ap_CS_fsm_state33) & (icmp_ln77_fu_785_p2 == 1'd0))) begin
        xp_reg_757 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state39)) begin
        yp_reg_735 <= yp_1_reg_856;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        yp_reg_735 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln78_fu_797_p2 == 1'd0) & (in0_V_TVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state34))) begin
        add_ln78_reg_865 <= add_ln78_fu_791_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln78_fu_797_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state34))) begin
        buf_V_addr_65_reg_883 <= zext_ln79_fu_817_p1;
        in0_V_read_reg_878 <= in0_V_TDATA;
        select_ln78_reg_873 <= select_ln78_fu_809_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        icmp_ln89_reg_899 <= icmp_ln89_fu_845_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        yp_1_reg_856 <= yp_1_fu_779_p2;
    end
end

always @ (*) begin
    if ((icmp_ln89_fu_845_p2 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state37 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state37 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state40) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state40)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln89_fu_845_p2 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        buf_V_address0 = zext_ln89_fu_851_p1;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        buf_V_address0 = zext_ln79_fu_817_p1;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        buf_V_address0 = 64'd63;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        buf_V_address0 = 64'd61;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        buf_V_address0 = 64'd59;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        buf_V_address0 = 64'd57;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        buf_V_address0 = 64'd55;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        buf_V_address0 = 64'd53;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        buf_V_address0 = 64'd51;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        buf_V_address0 = 64'd49;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        buf_V_address0 = 64'd47;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        buf_V_address0 = 64'd45;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        buf_V_address0 = 64'd43;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        buf_V_address0 = 64'd41;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        buf_V_address0 = 64'd39;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        buf_V_address0 = 64'd37;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        buf_V_address0 = 64'd35;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        buf_V_address0 = 64'd33;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        buf_V_address0 = 64'd31;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        buf_V_address0 = 64'd29;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        buf_V_address0 = 64'd27;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        buf_V_address0 = 64'd25;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_address0 = 64'd23;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        buf_V_address0 = 64'd21;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_V_address0 = 64'd19;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        buf_V_address0 = 64'd17;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_address0 = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_address0 = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_address0 = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_V_address0 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_V_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_V_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        buf_V_address0 = 64'd1;
    end else begin
        buf_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        buf_V_address1 = buf_V_addr_65_reg_883;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        buf_V_address1 = 64'd62;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        buf_V_address1 = 64'd60;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        buf_V_address1 = 64'd58;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        buf_V_address1 = 64'd56;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        buf_V_address1 = 64'd54;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        buf_V_address1 = 64'd52;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        buf_V_address1 = 64'd50;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        buf_V_address1 = 64'd48;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        buf_V_address1 = 64'd46;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        buf_V_address1 = 64'd44;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        buf_V_address1 = 64'd42;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        buf_V_address1 = 64'd40;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        buf_V_address1 = 64'd38;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        buf_V_address1 = 64'd36;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        buf_V_address1 = 64'd34;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        buf_V_address1 = 64'd32;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        buf_V_address1 = 64'd30;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        buf_V_address1 = 64'd28;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        buf_V_address1 = 64'd26;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        buf_V_address1 = 64'd24;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_V_address1 = 64'd22;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        buf_V_address1 = 64'd20;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        buf_V_address1 = 64'd18;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        buf_V_address1 = 64'd16;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_V_address1 = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        buf_V_address1 = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_address1 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_V_address1 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_V_address1 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_V_address1 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_V_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        buf_V_address1 = 64'd0;
    end else begin
        buf_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state32) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln89_fu_845_p2 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1)) | (~((icmp_ln78_fu_797_p2 == 1'd0) & (in0_V_TVALID == 1'b0)) & (1'b1 == ap_CS_fsm_state34)))) begin
        buf_V_ce0 = 1'b1;
    end else begin
        buf_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state32) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((in0_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state35)))) begin
        buf_V_ce1 = 1'b1;
    end else begin
        buf_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state35)) begin
        buf_V_d1 = or_ln709_fu_827_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state32))) begin
        buf_V_d1 = 64'd0;
    end else begin
        buf_V_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state32) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln89_fu_845_p2 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1)))) begin
        buf_V_we0 = 1'b1;
    end else begin
        buf_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state32) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((in0_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state35)))) begin
        buf_V_we1 = 1'b1;
    end else begin
        buf_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state35) | ((icmp_ln78_fu_797_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state34)))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((in0_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state35)) | (~((icmp_ln78_fu_797_p2 == 1'd0) & (in0_V_TVALID == 1'b0)) & (icmp_ln78_fu_797_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state34)))) begin
        in0_V_TREADY = 1'b1;
    end else begin
        in0_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln89_reg_899 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        out_V_TDATA_blk_n = out_V_TREADY;
    end else begin
        out_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln89_reg_899 == 1'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        out_V_TVALID = 1'b1;
    end else begin
        out_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            if (((1'b1 == ap_CS_fsm_state33) & (icmp_ln77_fu_785_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state40;
            end
        end
        ap_ST_fsm_state34 : begin
            if ((~((icmp_ln78_fu_797_p2 == 1'd0) & (in0_V_TVALID == 1'b0)) & (icmp_ln78_fu_797_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state34))) begin
                ap_NS_fsm = ap_ST_fsm_state35;
            end else if ((~((icmp_ln78_fu_797_p2 == 1'd0) & (in0_V_TVALID == 1'b0)) & (icmp_ln78_fu_797_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state34))) begin
                ap_NS_fsm = ap_ST_fsm_state36;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end
        end
        ap_ST_fsm_state35 : begin
            if (((in0_V_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state35))) begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state35;
            end
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if (~((1'b0 == ap_block_pp1_stage0_subdone) & (icmp_ln89_fu_845_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((1'b0 == ap_block_pp1_stage0_subdone) & (icmp_ln89_fu_845_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state39;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln78_fu_791_p2 = (indvar_flatten_reg_746 + 8'd1);

assign add_ln79_fu_834_p2 = (select_ln78_reg_873 + 7'd1);

assign add_ln89_fu_839_p2 = (outpix_reg_768 + 7'd1);

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage0_01001 = ((icmp_ln89_reg_899 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_pp1_stage0_11001 = ((ap_enable_reg_pp1_iter1 == 1'b1) & ((1'b1 == ap_block_state38_io) | ((icmp_ln89_reg_899 == 1'd0) & (out_V_TREADY == 1'b0))));
end

always @ (*) begin
    ap_block_pp1_stage0_subdone = ((ap_enable_reg_pp1_iter1 == 1'b1) & ((1'b1 == ap_block_state38_io) | ((icmp_ln89_reg_899 == 1'd0) & (out_V_TREADY == 1'b0))));
end

always @ (*) begin
    ap_block_state34 = ((icmp_ln78_fu_797_p2 == 1'd0) & (in0_V_TVALID == 1'b0));
end

assign ap_block_state37_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state38_io = ((icmp_ln89_reg_899 == 1'd0) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state38_pp1_stage0_iter1 = ((icmp_ln89_reg_899 == 1'd0) & (out_V_TREADY == 1'b0));
end

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign icmp_ln77_fu_785_p2 = ((yp_reg_735 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln78_fu_797_p2 = ((indvar_flatten_reg_746 == 8'd128) ? 1'b1 : 1'b0);

assign icmp_ln79_fu_803_p2 = ((xp_reg_757 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln89_fu_845_p2 = ((outpix_reg_768 == 7'd64) ? 1'b1 : 1'b0);

assign or_ln709_1_fu_822_p2 = (in0_V_read_reg_878 | buf_V_q0);

assign or_ln709_fu_827_p2 = (or_ln709_1_fu_822_p2 | in0_V_TDATA);

assign out_V_TDATA = buf_V_q0;

assign select_ln78_fu_809_p3 = ((icmp_ln79_fu_803_p2[0:0] == 1'b1) ? 7'd0 : xp_reg_757);

assign yp_1_fu_779_p2 = (yp_reg_735 + 7'd1);

assign zext_ln79_fu_817_p1 = select_ln78_fu_809_p3;

assign zext_ln89_fu_851_p1 = outpix_reg_768;

endmodule //StreamingMaxPool_Batch_1_StreamingMaxPool_128u_2u_64u_s
