// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module StreamingFCLayer_Batch_0_Matrix_Vector_Activate_Stream_Batch_27u_64u_27u_2u_Slice_ap_int_8u_Slice_ap_int_2_2u_Recast_Binary_ap_uint_1_ap_uint_216_ap_uint_4_ThresholdsActivation_32u_2u_2u_ap_int_13_ap_int_2_1_less_equal_ap_int_13_ap_resource_lut_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in0_V_TDATA,
        in0_V_TVALID,
        in0_V_TREADY,
        out_V_TDATA,
        out_V_TVALID,
        out_V_TREADY,
        weights_V_TDATA,
        weights_V_TVALID,
        weights_V_TREADY
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state4 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [215:0] in0_V_TDATA;
input   in0_V_TVALID;
output   in0_V_TREADY;
output  [7:0] out_V_TDATA;
output   out_V_TVALID;
input   out_V_TREADY;
input  [55:0] weights_V_TDATA;
input   weights_V_TVALID;
output   weights_V_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in0_V_TREADY;
reg out_V_TVALID;
reg weights_V_TREADY;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [4:0] threshs_m_thresholds_V_0_0_address0;
reg    threshs_m_thresholds_V_0_0_ce0;
wire   [12:0] threshs_m_thresholds_V_0_0_q0;
wire   [4:0] threshs_m_thresholds_V_0_1_address0;
reg    threshs_m_thresholds_V_0_1_ce0;
wire   [12:0] threshs_m_thresholds_V_0_1_q0;
wire   [4:0] threshs_m_thresholds_V_1_0_address0;
reg    threshs_m_thresholds_V_1_0_ce0;
wire   [12:0] threshs_m_thresholds_V_1_0_q0;
wire   [4:0] threshs_m_thresholds_V_1_1_address0;
reg    threshs_m_thresholds_V_1_1_ce0;
wire   [12:0] threshs_m_thresholds_V_1_1_q0;
reg    in0_V_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln248_fu_353_p2;
wire   [0:0] icmp_ln252_fu_359_p2;
reg    out_V_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter1;
reg   [0:0] icmp_ln248_reg_2501;
reg    weights_V_TDATA_blk_n;
reg   [21:0] i_reg_325;
reg   [31:0] nf_1_reg_336;
wire   [21:0] i_1_fu_347_p2;
reg    ap_predicate_op20_read_state2;
reg    ap_block_state2_pp0_stage0_iter0;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_state3_io;
reg    ap_block_pp0_stage0_11001;
reg   [55:0] weights_V_read_reg_2508;
wire   [0:0] trunc_ln674_fu_370_p1;
reg   [0:0] trunc_ln674_reg_2536;
reg   [0:0] tmp_reg_2541;
reg   [0:0] tmp_1_reg_2546;
reg   [0:0] tmp_6_reg_2551;
reg   [0:0] tmp_7_reg_2556;
reg   [0:0] tmp_9_reg_2561;
reg   [0:0] tmp_12_reg_2566;
reg   [0:0] tmp_14_reg_2571;
reg   [0:0] tmp_18_reg_2576;
reg   [0:0] tmp_19_reg_2581;
reg   [0:0] tmp_20_reg_2586;
reg   [0:0] tmp_21_reg_2591;
reg   [0:0] tmp_22_reg_2596;
reg   [0:0] tmp_23_reg_2601;
reg   [0:0] tmp_24_reg_2606;
reg   [0:0] tmp_26_reg_2611;
reg   [0:0] tmp_27_reg_2616;
reg   [0:0] tmp_28_reg_2621;
reg   [0:0] tmp_33_reg_2626;
reg   [0:0] tmp_34_reg_2631;
reg   [0:0] tmp_36_reg_2636;
reg   [0:0] tmp_39_reg_2641;
reg   [0:0] tmp_41_reg_2646;
reg   [0:0] tmp_45_reg_2651;
reg   [0:0] tmp_46_reg_2656;
reg   [0:0] tmp_47_reg_2661;
reg   [0:0] tmp_48_reg_2666;
reg   [0:0] tmp_49_reg_2671;
reg   [0:0] tmp_50_reg_2676;
reg   [0:0] tmp_51_reg_2681;
wire   [31:0] nf_2_fu_626_p3;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
wire   [63:0] idxprom2_i_fu_606_p1;
reg   [215:0] p_Val2_s_fu_250;
reg    ap_block_pp0_stage0_01001;
wire   [31:0] nf_fu_614_p2;
wire   [0:0] icmp_ln301_fu_620_p2;
wire   [7:0] trunc_ln674_1_fu_721_p1;
wire  signed [8:0] rhs_0_0_fu_725_p1;
wire   [8:0] sub_ln1347_fu_729_p2;
wire   [8:0] select_ln89_fu_735_p3;
wire   [7:0] p_Result_29_0_1_fu_746_p4;
wire  signed [8:0] rhs_0_1_fu_756_p1;
wire   [8:0] sub_ln1347_1_fu_760_p2;
wire   [8:0] select_ln89_1_fu_766_p3;
wire   [7:0] p_Result_29_0_2_fu_777_p4;
wire  signed [8:0] rhs_0_2_fu_787_p1;
wire   [8:0] sub_ln1347_2_fu_791_p2;
wire   [8:0] select_ln89_2_fu_797_p3;
wire   [7:0] p_Result_29_0_3_fu_808_p4;
wire  signed [8:0] rhs_0_3_fu_818_p1;
wire   [0:0] tmp_2_fu_637_p3;
wire   [8:0] sub_ln1347_3_fu_822_p2;
wire   [8:0] select_ln89_3_fu_828_p3;
wire   [7:0] p_Result_29_0_4_fu_840_p4;
wire  signed [8:0] rhs_0_4_fu_850_p1;
wire   [0:0] tmp_3_fu_644_p3;
wire   [8:0] sub_ln1347_4_fu_854_p2;
wire   [8:0] select_ln89_4_fu_860_p3;
wire   [7:0] p_Result_29_0_5_fu_872_p4;
wire  signed [8:0] rhs_0_5_fu_882_p1;
wire   [0:0] tmp_4_fu_651_p3;
wire   [8:0] sub_ln1347_5_fu_886_p2;
wire   [8:0] select_ln89_5_fu_892_p3;
wire   [7:0] p_Result_29_0_6_fu_904_p4;
wire  signed [8:0] rhs_0_6_fu_914_p1;
wire   [0:0] tmp_5_fu_658_p3;
wire   [8:0] sub_ln1347_6_fu_918_p2;
wire   [8:0] select_ln89_6_fu_924_p3;
wire   [7:0] p_Result_29_0_7_fu_936_p4;
wire  signed [8:0] rhs_0_7_fu_946_p1;
wire   [8:0] sub_ln1347_7_fu_950_p2;
wire   [8:0] select_ln89_7_fu_956_p3;
wire   [7:0] p_Result_29_0_8_fu_967_p4;
wire  signed [8:0] rhs_0_8_fu_977_p1;
wire   [8:0] sub_ln1347_8_fu_981_p2;
wire   [8:0] select_ln89_8_fu_987_p3;
wire   [7:0] p_Result_29_0_9_fu_998_p4;
wire  signed [8:0] rhs_0_9_fu_1008_p1;
wire   [0:0] tmp_8_fu_665_p3;
wire   [8:0] sub_ln1347_9_fu_1012_p2;
wire   [8:0] select_ln89_9_fu_1018_p3;
wire   [7:0] p_Result_29_0_s_fu_1030_p4;
wire  signed [8:0] rhs_0_10_fu_1040_p1;
wire   [8:0] sub_ln1347_10_fu_1044_p2;
wire   [8:0] select_ln89_10_fu_1050_p3;
wire   [7:0] p_Result_29_0_10_fu_1061_p4;
wire  signed [8:0] rhs_0_11_fu_1071_p1;
wire   [0:0] tmp_10_fu_672_p3;
wire   [8:0] sub_ln1347_11_fu_1075_p2;
wire   [8:0] select_ln89_11_fu_1081_p3;
wire   [7:0] p_Result_29_0_11_fu_1093_p4;
wire  signed [8:0] rhs_0_12_fu_1103_p1;
wire   [0:0] tmp_11_fu_679_p3;
wire   [8:0] sub_ln1347_12_fu_1107_p2;
wire   [8:0] select_ln89_12_fu_1113_p3;
wire   [7:0] p_Result_29_0_12_fu_1125_p4;
wire  signed [8:0] rhs_0_13_fu_1135_p1;
wire   [8:0] sub_ln1347_13_fu_1139_p2;
wire   [8:0] select_ln89_13_fu_1145_p3;
wire   [7:0] p_Result_29_0_13_fu_1156_p4;
wire  signed [8:0] rhs_0_14_fu_1166_p1;
wire   [0:0] tmp_13_fu_686_p3;
wire   [8:0] sub_ln1347_14_fu_1170_p2;
wire   [8:0] select_ln89_14_fu_1176_p3;
wire   [7:0] p_Result_29_0_14_fu_1188_p4;
wire  signed [8:0] rhs_0_15_fu_1198_p1;
wire   [8:0] sub_ln1347_15_fu_1202_p2;
wire   [8:0] select_ln89_15_fu_1208_p3;
wire   [7:0] p_Result_29_0_15_fu_1219_p4;
wire  signed [8:0] rhs_0_16_fu_1229_p1;
wire   [0:0] tmp_15_fu_693_p3;
wire   [8:0] sub_ln1347_16_fu_1233_p2;
wire   [8:0] select_ln89_16_fu_1239_p3;
wire   [7:0] p_Result_29_0_16_fu_1251_p4;
wire  signed [8:0] rhs_0_17_fu_1261_p1;
wire   [0:0] tmp_16_fu_700_p3;
wire   [8:0] sub_ln1347_17_fu_1265_p2;
wire   [8:0] select_ln89_17_fu_1271_p3;
wire   [7:0] p_Result_29_0_17_fu_1283_p4;
wire  signed [8:0] rhs_0_18_fu_1293_p1;
wire   [0:0] tmp_17_fu_707_p3;
wire   [8:0] sub_ln1347_18_fu_1297_p2;
wire   [8:0] select_ln89_18_fu_1303_p3;
wire   [7:0] p_Result_29_0_18_fu_1315_p4;
wire  signed [8:0] rhs_0_19_fu_1325_p1;
wire   [8:0] sub_ln1347_19_fu_1329_p2;
wire   [8:0] select_ln89_19_fu_1335_p3;
wire   [7:0] p_Result_29_0_19_fu_1346_p4;
wire  signed [8:0] rhs_0_20_fu_1356_p1;
wire   [8:0] sub_ln1347_20_fu_1360_p2;
wire   [8:0] select_ln89_20_fu_1366_p3;
wire   [7:0] p_Result_29_0_20_fu_1377_p4;
wire  signed [8:0] rhs_0_21_fu_1387_p1;
wire   [8:0] sub_ln1347_21_fu_1391_p2;
wire   [8:0] select_ln89_21_fu_1397_p3;
wire   [7:0] p_Result_29_0_21_fu_1408_p4;
wire  signed [8:0] rhs_0_22_fu_1418_p1;
wire   [8:0] sub_ln1347_22_fu_1422_p2;
wire   [8:0] select_ln89_22_fu_1428_p3;
wire   [7:0] p_Result_29_0_22_fu_1439_p4;
wire  signed [8:0] rhs_0_23_fu_1449_p1;
wire   [8:0] sub_ln1347_23_fu_1453_p2;
wire   [8:0] select_ln89_23_fu_1459_p3;
wire   [7:0] p_Result_29_0_23_fu_1470_p4;
wire  signed [8:0] rhs_0_24_fu_1480_p1;
wire   [8:0] sub_ln1347_24_fu_1484_p2;
wire   [8:0] select_ln89_24_fu_1490_p3;
wire   [7:0] p_Result_29_0_24_fu_1501_p4;
wire  signed [8:0] rhs_0_25_fu_1511_p1;
wire   [8:0] sub_ln1347_25_fu_1515_p2;
wire   [8:0] select_ln89_25_fu_1521_p3;
wire   [7:0] p_Result_29_0_25_fu_1532_p4;
wire  signed [8:0] rhs_0_26_fu_1542_p1;
wire   [0:0] tmp_25_fu_714_p3;
wire   [8:0] sub_ln1347_26_fu_1546_p2;
wire   [8:0] select_ln89_26_fu_1552_p3;
wire  signed [9:0] sext_ln674_25_fu_1528_p1;
wire  signed [9:0] sext_ln674_23_fu_1466_p1;
wire   [9:0] add_ln691_fu_1564_p2;
wire  signed [9:0] sext_ln674_24_fu_1497_p1;
wire   [9:0] add_ln691_1_fu_1570_p2;
wire  signed [9:0] sext_ln674_19_fu_1342_p1;
wire  signed [9:0] sext_ln674_21_fu_1404_p1;
wire   [9:0] add_ln691_2_fu_1580_p2;
wire  signed [9:0] sext_ln674_22_fu_1435_p1;
wire   [9:0] add_ln691_3_fu_1586_p2;
wire  signed [10:0] sext_ln691_2_fu_1592_p1;
wire  signed [10:0] sext_ln691_1_fu_1576_p1;
wire   [10:0] add_ln691_4_fu_1596_p2;
wire  signed [9:0] sext_ln674_13_fu_1152_p1;
wire  signed [9:0] sext_ln674_15_fu_1215_p1;
wire   [9:0] add_ln691_5_fu_1606_p2;
wire  signed [9:0] sext_ln674_20_fu_1373_p1;
wire   [9:0] add_ln691_6_fu_1612_p2;
wire  signed [9:0] sext_ln674_14_fu_1184_p1;
wire  signed [9:0] sext_ln674_16_fu_1247_p1;
wire   [9:0] add_ln691_7_fu_1622_p2;
wire  signed [9:0] sext_ln674_18_fu_1311_p1;
wire  signed [9:0] sext_ln674_17_fu_1279_p1;
wire   [9:0] add_ln691_8_fu_1632_p2;
wire  signed [10:0] sext_ln691_6_fu_1638_p1;
wire  signed [10:0] sext_ln691_5_fu_1628_p1;
wire   [10:0] add_ln691_9_fu_1642_p2;
wire  signed [10:0] sext_ln691_4_fu_1618_p1;
wire   [10:0] add_ln691_10_fu_1648_p2;
wire  signed [11:0] sext_ln691_7_fu_1654_p1;
wire  signed [11:0] sext_ln691_3_fu_1602_p1;
wire   [11:0] add_ln691_11_fu_1658_p2;
wire  signed [9:0] sext_ln674_2_fu_804_p1;
wire  signed [9:0] sext_ln674_fu_742_p1;
wire   [9:0] add_ln691_12_fu_1668_p2;
wire  signed [9:0] sext_ln674_1_fu_773_p1;
wire   [9:0] add_ln691_13_fu_1674_p2;
wire  signed [9:0] sext_ln674_3_fu_836_p1;
wire  signed [9:0] sext_ln674_5_fu_900_p1;
wire   [9:0] add_ln691_14_fu_1684_p2;
wire  signed [9:0] sext_ln674_4_fu_868_p1;
wire  signed [9:0] sext_ln674_6_fu_932_p1;
wire   [9:0] add_ln691_15_fu_1694_p2;
wire  signed [10:0] sext_ln691_11_fu_1700_p1;
wire  signed [10:0] sext_ln691_10_fu_1690_p1;
wire   [10:0] add_ln691_16_fu_1704_p2;
wire  signed [10:0] sext_ln691_9_fu_1680_p1;
wire   [10:0] add_ln691_17_fu_1710_p2;
wire  signed [9:0] sext_ln674_7_fu_963_p1;
wire  signed [9:0] sext_ln674_10_fu_1057_p1;
wire   [9:0] add_ln691_18_fu_1720_p2;
wire  signed [9:0] sext_ln674_8_fu_994_p1;
wire   [9:0] add_ln691_19_fu_1726_p2;
wire  signed [9:0] sext_ln674_9_fu_1026_p1;
wire  signed [9:0] sext_ln674_12_fu_1121_p1;
wire   [9:0] add_ln691_20_fu_1736_p2;
wire  signed [9:0] sext_ln674_11_fu_1089_p1;
wire  signed [9:0] sext_ln691_fu_1560_p1;
wire   [9:0] add_ln691_21_fu_1746_p2;
wire  signed [10:0] sext_ln691_15_fu_1752_p1;
wire  signed [10:0] sext_ln691_14_fu_1742_p1;
wire   [10:0] add_ln691_22_fu_1756_p2;
wire  signed [10:0] sext_ln691_13_fu_1732_p1;
wire   [10:0] add_ln691_23_fu_1762_p2;
wire  signed [11:0] sext_ln691_16_fu_1768_p1;
wire  signed [11:0] sext_ln691_12_fu_1716_p1;
wire   [11:0] add_ln691_24_fu_1772_p2;
wire  signed [12:0] sext_ln691_17_fu_1778_p1;
wire  signed [12:0] sext_ln691_8_fu_1664_p1;
wire   [8:0] select_ln89_27_fu_1872_p3;
wire   [8:0] select_ln89_28_fu_1883_p3;
wire   [8:0] select_ln89_29_fu_1894_p3;
wire   [0:0] tmp_29_fu_1788_p3;
wire   [8:0] select_ln89_30_fu_1905_p3;
wire   [0:0] tmp_30_fu_1795_p3;
wire   [8:0] select_ln89_31_fu_1917_p3;
wire   [0:0] tmp_31_fu_1802_p3;
wire   [8:0] select_ln89_32_fu_1929_p3;
wire   [0:0] tmp_32_fu_1809_p3;
wire   [8:0] select_ln89_33_fu_1941_p3;
wire   [8:0] select_ln89_34_fu_1953_p3;
wire   [8:0] select_ln89_35_fu_1964_p3;
wire   [0:0] tmp_35_fu_1816_p3;
wire   [8:0] select_ln89_36_fu_1975_p3;
wire   [8:0] select_ln89_37_fu_1987_p3;
wire   [0:0] tmp_37_fu_1823_p3;
wire   [8:0] select_ln89_38_fu_1998_p3;
wire   [0:0] tmp_38_fu_1830_p3;
wire   [8:0] select_ln89_39_fu_2010_p3;
wire   [8:0] select_ln89_40_fu_2022_p3;
wire   [0:0] tmp_40_fu_1837_p3;
wire   [8:0] select_ln89_41_fu_2033_p3;
wire   [8:0] select_ln89_42_fu_2045_p3;
wire   [0:0] tmp_42_fu_1844_p3;
wire   [8:0] select_ln89_43_fu_2056_p3;
wire   [0:0] tmp_43_fu_1851_p3;
wire   [8:0] select_ln89_44_fu_2068_p3;
wire   [0:0] tmp_44_fu_1858_p3;
wire   [8:0] select_ln89_45_fu_2080_p3;
wire   [8:0] select_ln89_46_fu_2092_p3;
wire   [8:0] select_ln89_47_fu_2103_p3;
wire   [8:0] select_ln89_48_fu_2114_p3;
wire   [8:0] select_ln89_49_fu_2125_p3;
wire   [8:0] select_ln89_50_fu_2136_p3;
wire   [8:0] select_ln89_51_fu_2147_p3;
wire   [8:0] select_ln89_52_fu_2158_p3;
wire   [0:0] tmp_52_fu_1865_p3;
wire   [8:0] select_ln89_53_fu_2169_p3;
wire  signed [9:0] sext_ln89_25_fu_2165_p1;
wire  signed [9:0] sext_ln89_23_fu_2143_p1;
wire   [9:0] add_ln691_26_fu_2181_p2;
wire  signed [9:0] sext_ln89_24_fu_2154_p1;
wire   [9:0] add_ln691_27_fu_2187_p2;
wire  signed [9:0] sext_ln89_19_fu_2099_p1;
wire  signed [9:0] sext_ln89_21_fu_2121_p1;
wire   [9:0] add_ln691_28_fu_2197_p2;
wire  signed [9:0] sext_ln89_22_fu_2132_p1;
wire   [9:0] add_ln691_29_fu_2203_p2;
wire  signed [10:0] sext_ln691_20_fu_2209_p1;
wire  signed [10:0] sext_ln691_19_fu_2193_p1;
wire   [10:0] add_ln691_30_fu_2213_p2;
wire  signed [9:0] sext_ln89_13_fu_2029_p1;
wire  signed [9:0] sext_ln89_15_fu_2052_p1;
wire   [9:0] add_ln691_31_fu_2223_p2;
wire  signed [9:0] sext_ln89_20_fu_2110_p1;
wire   [9:0] add_ln691_32_fu_2229_p2;
wire  signed [9:0] sext_ln89_14_fu_2041_p1;
wire  signed [9:0] sext_ln89_16_fu_2064_p1;
wire   [9:0] add_ln691_33_fu_2239_p2;
wire  signed [9:0] sext_ln89_18_fu_2088_p1;
wire  signed [9:0] sext_ln89_17_fu_2076_p1;
wire   [9:0] add_ln691_34_fu_2249_p2;
wire  signed [10:0] sext_ln691_24_fu_2255_p1;
wire  signed [10:0] sext_ln691_23_fu_2245_p1;
wire   [10:0] add_ln691_35_fu_2259_p2;
wire  signed [10:0] sext_ln691_22_fu_2235_p1;
wire   [10:0] add_ln691_36_fu_2265_p2;
wire  signed [11:0] sext_ln691_25_fu_2271_p1;
wire  signed [11:0] sext_ln691_21_fu_2219_p1;
wire   [11:0] add_ln691_37_fu_2275_p2;
wire  signed [9:0] sext_ln89_2_fu_1901_p1;
wire  signed [9:0] sext_ln89_fu_1879_p1;
wire   [9:0] add_ln691_38_fu_2285_p2;
wire  signed [9:0] sext_ln89_1_fu_1890_p1;
wire   [9:0] add_ln691_39_fu_2291_p2;
wire  signed [9:0] sext_ln89_3_fu_1913_p1;
wire  signed [9:0] sext_ln89_5_fu_1937_p1;
wire   [9:0] add_ln691_40_fu_2301_p2;
wire  signed [9:0] sext_ln89_4_fu_1925_p1;
wire  signed [9:0] sext_ln89_6_fu_1949_p1;
wire   [9:0] add_ln691_41_fu_2311_p2;
wire  signed [10:0] sext_ln691_29_fu_2317_p1;
wire  signed [10:0] sext_ln691_28_fu_2307_p1;
wire   [10:0] add_ln691_42_fu_2321_p2;
wire  signed [10:0] sext_ln691_27_fu_2297_p1;
wire   [10:0] add_ln691_43_fu_2327_p2;
wire  signed [9:0] sext_ln89_7_fu_1960_p1;
wire  signed [9:0] sext_ln89_10_fu_1994_p1;
wire   [9:0] add_ln691_44_fu_2337_p2;
wire  signed [9:0] sext_ln89_8_fu_1971_p1;
wire   [9:0] add_ln691_45_fu_2343_p2;
wire  signed [9:0] sext_ln89_9_fu_1983_p1;
wire  signed [9:0] sext_ln89_12_fu_2018_p1;
wire   [9:0] add_ln691_46_fu_2353_p2;
wire  signed [9:0] sext_ln89_11_fu_2006_p1;
wire  signed [9:0] sext_ln691_18_fu_2177_p1;
wire   [9:0] add_ln691_47_fu_2363_p2;
wire  signed [10:0] sext_ln691_33_fu_2369_p1;
wire  signed [10:0] sext_ln691_32_fu_2359_p1;
wire   [10:0] add_ln691_48_fu_2373_p2;
wire  signed [10:0] sext_ln691_31_fu_2349_p1;
wire   [10:0] add_ln691_49_fu_2379_p2;
wire  signed [11:0] sext_ln691_34_fu_2385_p1;
wire  signed [11:0] sext_ln691_30_fu_2333_p1;
wire   [11:0] add_ln691_50_fu_2389_p2;
wire  signed [12:0] sext_ln691_35_fu_2395_p1;
wire  signed [12:0] sext_ln691_26_fu_2281_p1;
wire   [12:0] add_ln691_25_fu_1782_p2;
wire   [0:0] result_V_fu_2405_p2;
wire   [0:0] icmp_ln890_fu_2419_p2;
wire   [0:0] xor_ln890_fu_2425_p2;
wire   [1:0] select_ln183_fu_2411_p3;
wire   [1:0] zext_ln691_fu_2431_p1;
wire   [12:0] add_ln691_51_fu_2399_p2;
wire   [0:0] result_V_2_fu_2441_p2;
wire   [0:0] icmp_ln890_1_fu_2455_p2;
wire   [0:0] xor_ln890_1_fu_2461_p2;
wire   [1:0] select_ln183_1_fu_2447_p3;
wire   [1:0] zext_ln691_1_fu_2467_p1;
wire   [1:0] result_V_3_fu_2471_p2;
wire   [1:0] result_V_1_fu_2435_p2;
wire   [3:0] p_Result_s_fu_2477_p3;
wire    ap_CS_fsm_state4;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

StreamingFCLayer_Batch_0_Matrix_Vector_Activate_Stream_Batch_27u_64u_27u_2u_Slice_ap_int_8u_Slice_ap_ibkb #(
    .DataWidth( 13 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
threshs_m_thresholds_V_0_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_V_0_0_address0),
    .ce0(threshs_m_thresholds_V_0_0_ce0),
    .q0(threshs_m_thresholds_V_0_0_q0)
);

StreamingFCLayer_Batch_0_Matrix_Vector_Activate_Stream_Batch_27u_64u_27u_2u_Slice_ap_int_8u_Slice_ap_icud #(
    .DataWidth( 13 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
threshs_m_thresholds_V_0_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_V_0_1_address0),
    .ce0(threshs_m_thresholds_V_0_1_ce0),
    .q0(threshs_m_thresholds_V_0_1_q0)
);

StreamingFCLayer_Batch_0_Matrix_Vector_Activate_Stream_Batch_27u_64u_27u_2u_Slice_ap_int_8u_Slice_ap_idEe #(
    .DataWidth( 13 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
threshs_m_thresholds_V_1_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_V_1_0_address0),
    .ce0(threshs_m_thresholds_V_1_0_ce0),
    .q0(threshs_m_thresholds_V_1_0_q0)
);

StreamingFCLayer_Batch_0_Matrix_Vector_Activate_Stream_Batch_27u_64u_27u_2u_Slice_ap_int_8u_Slice_ap_ieOg #(
    .DataWidth( 13 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
threshs_m_thresholds_V_1_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(threshs_m_thresholds_V_1_1_address0),
    .ce0(threshs_m_thresholds_V_1_1_ce0),
    .q0(threshs_m_thresholds_V_1_1_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln248_fu_353_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_reg_325 <= i_1_fu_347_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_325 <= 22'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln248_fu_353_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        nf_1_reg_336 <= nf_2_fu_626_p3;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        nf_1_reg_336 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln248_reg_2501 <= icmp_ln248_fu_353_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln252_fu_359_p2 == 1'd1) & (icmp_ln248_fu_353_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_Val2_s_fu_250 <= in0_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln248_fu_353_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_12_reg_2566 <= weights_V_TDATA[32'd13];
        tmp_14_reg_2571 <= weights_V_TDATA[32'd15];
        tmp_18_reg_2576 <= weights_V_TDATA[32'd19];
        tmp_19_reg_2581 <= weights_V_TDATA[32'd20];
        tmp_1_reg_2546 <= weights_V_TDATA[32'd2];
        tmp_20_reg_2586 <= weights_V_TDATA[32'd21];
        tmp_21_reg_2591 <= weights_V_TDATA[32'd22];
        tmp_22_reg_2596 <= weights_V_TDATA[32'd23];
        tmp_23_reg_2601 <= weights_V_TDATA[32'd24];
        tmp_24_reg_2606 <= weights_V_TDATA[32'd25];
        tmp_26_reg_2611 <= weights_V_TDATA[32'd27];
        tmp_27_reg_2616 <= weights_V_TDATA[32'd28];
        tmp_28_reg_2621 <= weights_V_TDATA[32'd29];
        tmp_33_reg_2626 <= weights_V_TDATA[32'd34];
        tmp_34_reg_2631 <= weights_V_TDATA[32'd35];
        tmp_36_reg_2636 <= weights_V_TDATA[32'd37];
        tmp_39_reg_2641 <= weights_V_TDATA[32'd40];
        tmp_41_reg_2646 <= weights_V_TDATA[32'd42];
        tmp_45_reg_2651 <= weights_V_TDATA[32'd46];
        tmp_46_reg_2656 <= weights_V_TDATA[32'd47];
        tmp_47_reg_2661 <= weights_V_TDATA[32'd48];
        tmp_48_reg_2666 <= weights_V_TDATA[32'd49];
        tmp_49_reg_2671 <= weights_V_TDATA[32'd50];
        tmp_50_reg_2676 <= weights_V_TDATA[32'd51];
        tmp_51_reg_2681 <= weights_V_TDATA[32'd52];
        tmp_6_reg_2551 <= weights_V_TDATA[32'd7];
        tmp_7_reg_2556 <= weights_V_TDATA[32'd8];
        tmp_9_reg_2561 <= weights_V_TDATA[32'd10];
        tmp_reg_2541 <= weights_V_TDATA[32'd1];
        trunc_ln674_reg_2536 <= trunc_ln674_fu_370_p1;
        weights_V_read_reg_2508 <= weights_V_TDATA;
    end
end

always @ (*) begin
    if ((icmp_ln248_fu_353_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln252_fu_359_p2 == 1'd1) & (icmp_ln248_fu_353_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op20_read_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in0_V_TREADY = 1'b1;
    end else begin
        in0_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln248_reg_2501 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_V_TDATA_blk_n = out_V_TREADY;
    end else begin
        out_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln248_reg_2501 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_V_TVALID = 1'b1;
    end else begin
        out_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        threshs_m_thresholds_V_0_0_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_V_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        threshs_m_thresholds_V_0_1_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_V_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        threshs_m_thresholds_V_1_0_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_V_1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        threshs_m_thresholds_V_1_1_ce0 = 1'b1;
    end else begin
        threshs_m_thresholds_V_1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln248_fu_353_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_V_TDATA_blk_n = weights_V_TVALID;
    end else begin
        weights_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln248_fu_353_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        weights_V_TREADY = 1'b1;
    end else begin
        weights_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((icmp_ln248_fu_353_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((icmp_ln248_fu_353_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln691_10_fu_1648_p2 = ($signed(add_ln691_9_fu_1642_p2) + $signed(sext_ln691_4_fu_1618_p1));

assign add_ln691_11_fu_1658_p2 = ($signed(sext_ln691_7_fu_1654_p1) + $signed(sext_ln691_3_fu_1602_p1));

assign add_ln691_12_fu_1668_p2 = ($signed(sext_ln674_2_fu_804_p1) + $signed(sext_ln674_fu_742_p1));

assign add_ln691_13_fu_1674_p2 = ($signed(add_ln691_12_fu_1668_p2) + $signed(sext_ln674_1_fu_773_p1));

assign add_ln691_14_fu_1684_p2 = ($signed(sext_ln674_3_fu_836_p1) + $signed(sext_ln674_5_fu_900_p1));

assign add_ln691_15_fu_1694_p2 = ($signed(sext_ln674_4_fu_868_p1) + $signed(sext_ln674_6_fu_932_p1));

assign add_ln691_16_fu_1704_p2 = ($signed(sext_ln691_11_fu_1700_p1) + $signed(sext_ln691_10_fu_1690_p1));

assign add_ln691_17_fu_1710_p2 = ($signed(add_ln691_16_fu_1704_p2) + $signed(sext_ln691_9_fu_1680_p1));

assign add_ln691_18_fu_1720_p2 = ($signed(sext_ln674_7_fu_963_p1) + $signed(sext_ln674_10_fu_1057_p1));

assign add_ln691_19_fu_1726_p2 = ($signed(add_ln691_18_fu_1720_p2) + $signed(sext_ln674_8_fu_994_p1));

assign add_ln691_1_fu_1570_p2 = ($signed(add_ln691_fu_1564_p2) + $signed(sext_ln674_24_fu_1497_p1));

assign add_ln691_20_fu_1736_p2 = ($signed(sext_ln674_9_fu_1026_p1) + $signed(sext_ln674_12_fu_1121_p1));

assign add_ln691_21_fu_1746_p2 = ($signed(sext_ln674_11_fu_1089_p1) + $signed(sext_ln691_fu_1560_p1));

assign add_ln691_22_fu_1756_p2 = ($signed(sext_ln691_15_fu_1752_p1) + $signed(sext_ln691_14_fu_1742_p1));

assign add_ln691_23_fu_1762_p2 = ($signed(add_ln691_22_fu_1756_p2) + $signed(sext_ln691_13_fu_1732_p1));

assign add_ln691_24_fu_1772_p2 = ($signed(sext_ln691_16_fu_1768_p1) + $signed(sext_ln691_12_fu_1716_p1));

assign add_ln691_25_fu_1782_p2 = ($signed(sext_ln691_17_fu_1778_p1) + $signed(sext_ln691_8_fu_1664_p1));

assign add_ln691_26_fu_2181_p2 = ($signed(sext_ln89_25_fu_2165_p1) + $signed(sext_ln89_23_fu_2143_p1));

assign add_ln691_27_fu_2187_p2 = ($signed(add_ln691_26_fu_2181_p2) + $signed(sext_ln89_24_fu_2154_p1));

assign add_ln691_28_fu_2197_p2 = ($signed(sext_ln89_19_fu_2099_p1) + $signed(sext_ln89_21_fu_2121_p1));

assign add_ln691_29_fu_2203_p2 = ($signed(add_ln691_28_fu_2197_p2) + $signed(sext_ln89_22_fu_2132_p1));

assign add_ln691_2_fu_1580_p2 = ($signed(sext_ln674_19_fu_1342_p1) + $signed(sext_ln674_21_fu_1404_p1));

assign add_ln691_30_fu_2213_p2 = ($signed(sext_ln691_20_fu_2209_p1) + $signed(sext_ln691_19_fu_2193_p1));

assign add_ln691_31_fu_2223_p2 = ($signed(sext_ln89_13_fu_2029_p1) + $signed(sext_ln89_15_fu_2052_p1));

assign add_ln691_32_fu_2229_p2 = ($signed(add_ln691_31_fu_2223_p2) + $signed(sext_ln89_20_fu_2110_p1));

assign add_ln691_33_fu_2239_p2 = ($signed(sext_ln89_14_fu_2041_p1) + $signed(sext_ln89_16_fu_2064_p1));

assign add_ln691_34_fu_2249_p2 = ($signed(sext_ln89_18_fu_2088_p1) + $signed(sext_ln89_17_fu_2076_p1));

assign add_ln691_35_fu_2259_p2 = ($signed(sext_ln691_24_fu_2255_p1) + $signed(sext_ln691_23_fu_2245_p1));

assign add_ln691_36_fu_2265_p2 = ($signed(add_ln691_35_fu_2259_p2) + $signed(sext_ln691_22_fu_2235_p1));

assign add_ln691_37_fu_2275_p2 = ($signed(sext_ln691_25_fu_2271_p1) + $signed(sext_ln691_21_fu_2219_p1));

assign add_ln691_38_fu_2285_p2 = ($signed(sext_ln89_2_fu_1901_p1) + $signed(sext_ln89_fu_1879_p1));

assign add_ln691_39_fu_2291_p2 = ($signed(add_ln691_38_fu_2285_p2) + $signed(sext_ln89_1_fu_1890_p1));

assign add_ln691_3_fu_1586_p2 = ($signed(add_ln691_2_fu_1580_p2) + $signed(sext_ln674_22_fu_1435_p1));

assign add_ln691_40_fu_2301_p2 = ($signed(sext_ln89_3_fu_1913_p1) + $signed(sext_ln89_5_fu_1937_p1));

assign add_ln691_41_fu_2311_p2 = ($signed(sext_ln89_4_fu_1925_p1) + $signed(sext_ln89_6_fu_1949_p1));

assign add_ln691_42_fu_2321_p2 = ($signed(sext_ln691_29_fu_2317_p1) + $signed(sext_ln691_28_fu_2307_p1));

assign add_ln691_43_fu_2327_p2 = ($signed(add_ln691_42_fu_2321_p2) + $signed(sext_ln691_27_fu_2297_p1));

assign add_ln691_44_fu_2337_p2 = ($signed(sext_ln89_7_fu_1960_p1) + $signed(sext_ln89_10_fu_1994_p1));

assign add_ln691_45_fu_2343_p2 = ($signed(add_ln691_44_fu_2337_p2) + $signed(sext_ln89_8_fu_1971_p1));

assign add_ln691_46_fu_2353_p2 = ($signed(sext_ln89_9_fu_1983_p1) + $signed(sext_ln89_12_fu_2018_p1));

assign add_ln691_47_fu_2363_p2 = ($signed(sext_ln89_11_fu_2006_p1) + $signed(sext_ln691_18_fu_2177_p1));

assign add_ln691_48_fu_2373_p2 = ($signed(sext_ln691_33_fu_2369_p1) + $signed(sext_ln691_32_fu_2359_p1));

assign add_ln691_49_fu_2379_p2 = ($signed(add_ln691_48_fu_2373_p2) + $signed(sext_ln691_31_fu_2349_p1));

assign add_ln691_4_fu_1596_p2 = ($signed(sext_ln691_2_fu_1592_p1) + $signed(sext_ln691_1_fu_1576_p1));

assign add_ln691_50_fu_2389_p2 = ($signed(sext_ln691_34_fu_2385_p1) + $signed(sext_ln691_30_fu_2333_p1));

assign add_ln691_51_fu_2399_p2 = ($signed(sext_ln691_35_fu_2395_p1) + $signed(sext_ln691_26_fu_2281_p1));

assign add_ln691_5_fu_1606_p2 = ($signed(sext_ln674_13_fu_1152_p1) + $signed(sext_ln674_15_fu_1215_p1));

assign add_ln691_6_fu_1612_p2 = ($signed(add_ln691_5_fu_1606_p2) + $signed(sext_ln674_20_fu_1373_p1));

assign add_ln691_7_fu_1622_p2 = ($signed(sext_ln674_14_fu_1184_p1) + $signed(sext_ln674_16_fu_1247_p1));

assign add_ln691_8_fu_1632_p2 = ($signed(sext_ln674_18_fu_1311_p1) + $signed(sext_ln674_17_fu_1279_p1));

assign add_ln691_9_fu_1642_p2 = ($signed(sext_ln691_6_fu_1638_p1) + $signed(sext_ln691_5_fu_1628_p1));

assign add_ln691_fu_1564_p2 = ($signed(sext_ln674_25_fu_1528_p1) + $signed(sext_ln674_23_fu_1466_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((icmp_ln248_reg_2501 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (out_V_TREADY == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (((icmp_ln248_fu_353_p2 == 1'd0) & (weights_V_TVALID == 1'b0)) | ((ap_predicate_op20_read_state2 == 1'b1) & (in0_V_TVALID == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state3_io) | ((icmp_ln248_reg_2501 == 1'd0) & (out_V_TREADY == 1'b0)))) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (((icmp_ln248_fu_353_p2 == 1'd0) & (weights_V_TVALID == 1'b0)) | ((ap_predicate_op20_read_state2 == 1'b1) & (in0_V_TVALID == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state3_io) | ((icmp_ln248_reg_2501 == 1'd0) & (out_V_TREADY == 1'b0)))) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (((icmp_ln248_fu_353_p2 == 1'd0) & (weights_V_TVALID == 1'b0)) | ((ap_predicate_op20_read_state2 == 1'b1) & (in0_V_TVALID == 1'b0)))));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = (((icmp_ln248_fu_353_p2 == 1'd0) & (weights_V_TVALID == 1'b0)) | ((ap_predicate_op20_read_state2 == 1'b1) & (in0_V_TVALID == 1'b0)));
end

always @ (*) begin
    ap_block_state3_io = ((icmp_ln248_reg_2501 == 1'd0) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((icmp_ln248_reg_2501 == 1'd0) & (out_V_TREADY == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op20_read_state2 = ((icmp_ln252_fu_359_p2 == 1'd1) & (icmp_ln248_fu_353_p2 == 1'd0));
end

assign i_1_fu_347_p2 = (i_reg_325 + 22'd1);

assign icmp_ln248_fu_353_p2 = ((i_reg_325 == 22'd2097152) ? 1'b1 : 1'b0);

assign icmp_ln252_fu_359_p2 = ((nf_1_reg_336 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln301_fu_620_p2 = ((nf_fu_614_p2 == 32'd32) ? 1'b1 : 1'b0);

assign icmp_ln890_1_fu_2455_p2 = (($signed(add_ln691_51_fu_2399_p2) < $signed(threshs_m_thresholds_V_1_1_q0)) ? 1'b1 : 1'b0);

assign icmp_ln890_fu_2419_p2 = (($signed(add_ln691_25_fu_1782_p2) < $signed(threshs_m_thresholds_V_0_1_q0)) ? 1'b1 : 1'b0);

assign idxprom2_i_fu_606_p1 = nf_1_reg_336;

assign nf_2_fu_626_p3 = ((icmp_ln301_fu_620_p2[0:0] == 1'b1) ? 32'd0 : nf_fu_614_p2);

assign nf_fu_614_p2 = (nf_1_reg_336 + 32'd1);

assign out_V_TDATA = p_Result_s_fu_2477_p3;

assign p_Result_29_0_10_fu_1061_p4 = {{p_Val2_s_fu_250[95:88]}};

assign p_Result_29_0_11_fu_1093_p4 = {{p_Val2_s_fu_250[103:96]}};

assign p_Result_29_0_12_fu_1125_p4 = {{p_Val2_s_fu_250[111:104]}};

assign p_Result_29_0_13_fu_1156_p4 = {{p_Val2_s_fu_250[119:112]}};

assign p_Result_29_0_14_fu_1188_p4 = {{p_Val2_s_fu_250[127:120]}};

assign p_Result_29_0_15_fu_1219_p4 = {{p_Val2_s_fu_250[135:128]}};

assign p_Result_29_0_16_fu_1251_p4 = {{p_Val2_s_fu_250[143:136]}};

assign p_Result_29_0_17_fu_1283_p4 = {{p_Val2_s_fu_250[151:144]}};

assign p_Result_29_0_18_fu_1315_p4 = {{p_Val2_s_fu_250[159:152]}};

assign p_Result_29_0_19_fu_1346_p4 = {{p_Val2_s_fu_250[167:160]}};

assign p_Result_29_0_1_fu_746_p4 = {{p_Val2_s_fu_250[15:8]}};

assign p_Result_29_0_20_fu_1377_p4 = {{p_Val2_s_fu_250[175:168]}};

assign p_Result_29_0_21_fu_1408_p4 = {{p_Val2_s_fu_250[183:176]}};

assign p_Result_29_0_22_fu_1439_p4 = {{p_Val2_s_fu_250[191:184]}};

assign p_Result_29_0_23_fu_1470_p4 = {{p_Val2_s_fu_250[199:192]}};

assign p_Result_29_0_24_fu_1501_p4 = {{p_Val2_s_fu_250[207:200]}};

assign p_Result_29_0_25_fu_1532_p4 = {{p_Val2_s_fu_250[215:208]}};

assign p_Result_29_0_2_fu_777_p4 = {{p_Val2_s_fu_250[23:16]}};

assign p_Result_29_0_3_fu_808_p4 = {{p_Val2_s_fu_250[31:24]}};

assign p_Result_29_0_4_fu_840_p4 = {{p_Val2_s_fu_250[39:32]}};

assign p_Result_29_0_5_fu_872_p4 = {{p_Val2_s_fu_250[47:40]}};

assign p_Result_29_0_6_fu_904_p4 = {{p_Val2_s_fu_250[55:48]}};

assign p_Result_29_0_7_fu_936_p4 = {{p_Val2_s_fu_250[63:56]}};

assign p_Result_29_0_8_fu_967_p4 = {{p_Val2_s_fu_250[71:64]}};

assign p_Result_29_0_9_fu_998_p4 = {{p_Val2_s_fu_250[79:72]}};

assign p_Result_29_0_s_fu_1030_p4 = {{p_Val2_s_fu_250[87:80]}};

assign p_Result_s_fu_2477_p3 = {{result_V_3_fu_2471_p2}, {result_V_1_fu_2435_p2}};

assign result_V_1_fu_2435_p2 = (select_ln183_fu_2411_p3 + zext_ln691_fu_2431_p1);

assign result_V_2_fu_2441_p2 = (($signed(threshs_m_thresholds_V_1_0_q0) > $signed(add_ln691_51_fu_2399_p2)) ? 1'b1 : 1'b0);

assign result_V_3_fu_2471_p2 = (select_ln183_1_fu_2447_p3 + zext_ln691_1_fu_2467_p1);

assign result_V_fu_2405_p2 = (($signed(threshs_m_thresholds_V_0_0_q0) > $signed(add_ln691_25_fu_1782_p2)) ? 1'b1 : 1'b0);

assign rhs_0_0_fu_725_p1 = $signed(trunc_ln674_1_fu_721_p1);

assign rhs_0_10_fu_1040_p1 = $signed(p_Result_29_0_s_fu_1030_p4);

assign rhs_0_11_fu_1071_p1 = $signed(p_Result_29_0_10_fu_1061_p4);

assign rhs_0_12_fu_1103_p1 = $signed(p_Result_29_0_11_fu_1093_p4);

assign rhs_0_13_fu_1135_p1 = $signed(p_Result_29_0_12_fu_1125_p4);

assign rhs_0_14_fu_1166_p1 = $signed(p_Result_29_0_13_fu_1156_p4);

assign rhs_0_15_fu_1198_p1 = $signed(p_Result_29_0_14_fu_1188_p4);

assign rhs_0_16_fu_1229_p1 = $signed(p_Result_29_0_15_fu_1219_p4);

assign rhs_0_17_fu_1261_p1 = $signed(p_Result_29_0_16_fu_1251_p4);

assign rhs_0_18_fu_1293_p1 = $signed(p_Result_29_0_17_fu_1283_p4);

assign rhs_0_19_fu_1325_p1 = $signed(p_Result_29_0_18_fu_1315_p4);

assign rhs_0_1_fu_756_p1 = $signed(p_Result_29_0_1_fu_746_p4);

assign rhs_0_20_fu_1356_p1 = $signed(p_Result_29_0_19_fu_1346_p4);

assign rhs_0_21_fu_1387_p1 = $signed(p_Result_29_0_20_fu_1377_p4);

assign rhs_0_22_fu_1418_p1 = $signed(p_Result_29_0_21_fu_1408_p4);

assign rhs_0_23_fu_1449_p1 = $signed(p_Result_29_0_22_fu_1439_p4);

assign rhs_0_24_fu_1480_p1 = $signed(p_Result_29_0_23_fu_1470_p4);

assign rhs_0_25_fu_1511_p1 = $signed(p_Result_29_0_24_fu_1501_p4);

assign rhs_0_26_fu_1542_p1 = $signed(p_Result_29_0_25_fu_1532_p4);

assign rhs_0_2_fu_787_p1 = $signed(p_Result_29_0_2_fu_777_p4);

assign rhs_0_3_fu_818_p1 = $signed(p_Result_29_0_3_fu_808_p4);

assign rhs_0_4_fu_850_p1 = $signed(p_Result_29_0_4_fu_840_p4);

assign rhs_0_5_fu_882_p1 = $signed(p_Result_29_0_5_fu_872_p4);

assign rhs_0_6_fu_914_p1 = $signed(p_Result_29_0_6_fu_904_p4);

assign rhs_0_7_fu_946_p1 = $signed(p_Result_29_0_7_fu_936_p4);

assign rhs_0_8_fu_977_p1 = $signed(p_Result_29_0_8_fu_967_p4);

assign rhs_0_9_fu_1008_p1 = $signed(p_Result_29_0_9_fu_998_p4);

assign select_ln183_1_fu_2447_p3 = ((result_V_2_fu_2441_p2[0:0] == 1'b1) ? 2'd3 : 2'd0);

assign select_ln183_fu_2411_p3 = ((result_V_fu_2405_p2[0:0] == 1'b1) ? 2'd3 : 2'd0);

assign select_ln89_10_fu_1050_p3 = ((tmp_9_reg_2561[0:0] == 1'b1) ? rhs_0_10_fu_1040_p1 : sub_ln1347_10_fu_1044_p2);

assign select_ln89_11_fu_1081_p3 = ((tmp_10_fu_672_p3[0:0] == 1'b1) ? rhs_0_11_fu_1071_p1 : sub_ln1347_11_fu_1075_p2);

assign select_ln89_12_fu_1113_p3 = ((tmp_11_fu_679_p3[0:0] == 1'b1) ? rhs_0_12_fu_1103_p1 : sub_ln1347_12_fu_1107_p2);

assign select_ln89_13_fu_1145_p3 = ((tmp_12_reg_2566[0:0] == 1'b1) ? rhs_0_13_fu_1135_p1 : sub_ln1347_13_fu_1139_p2);

assign select_ln89_14_fu_1176_p3 = ((tmp_13_fu_686_p3[0:0] == 1'b1) ? rhs_0_14_fu_1166_p1 : sub_ln1347_14_fu_1170_p2);

assign select_ln89_15_fu_1208_p3 = ((tmp_14_reg_2571[0:0] == 1'b1) ? rhs_0_15_fu_1198_p1 : sub_ln1347_15_fu_1202_p2);

assign select_ln89_16_fu_1239_p3 = ((tmp_15_fu_693_p3[0:0] == 1'b1) ? rhs_0_16_fu_1229_p1 : sub_ln1347_16_fu_1233_p2);

assign select_ln89_17_fu_1271_p3 = ((tmp_16_fu_700_p3[0:0] == 1'b1) ? rhs_0_17_fu_1261_p1 : sub_ln1347_17_fu_1265_p2);

assign select_ln89_18_fu_1303_p3 = ((tmp_17_fu_707_p3[0:0] == 1'b1) ? rhs_0_18_fu_1293_p1 : sub_ln1347_18_fu_1297_p2);

assign select_ln89_19_fu_1335_p3 = ((tmp_18_reg_2576[0:0] == 1'b1) ? rhs_0_19_fu_1325_p1 : sub_ln1347_19_fu_1329_p2);

assign select_ln89_1_fu_766_p3 = ((tmp_reg_2541[0:0] == 1'b1) ? rhs_0_1_fu_756_p1 : sub_ln1347_1_fu_760_p2);

assign select_ln89_20_fu_1366_p3 = ((tmp_19_reg_2581[0:0] == 1'b1) ? rhs_0_20_fu_1356_p1 : sub_ln1347_20_fu_1360_p2);

assign select_ln89_21_fu_1397_p3 = ((tmp_20_reg_2586[0:0] == 1'b1) ? rhs_0_21_fu_1387_p1 : sub_ln1347_21_fu_1391_p2);

assign select_ln89_22_fu_1428_p3 = ((tmp_21_reg_2591[0:0] == 1'b1) ? rhs_0_22_fu_1418_p1 : sub_ln1347_22_fu_1422_p2);

assign select_ln89_23_fu_1459_p3 = ((tmp_22_reg_2596[0:0] == 1'b1) ? rhs_0_23_fu_1449_p1 : sub_ln1347_23_fu_1453_p2);

assign select_ln89_24_fu_1490_p3 = ((tmp_23_reg_2601[0:0] == 1'b1) ? rhs_0_24_fu_1480_p1 : sub_ln1347_24_fu_1484_p2);

assign select_ln89_25_fu_1521_p3 = ((tmp_24_reg_2606[0:0] == 1'b1) ? rhs_0_25_fu_1511_p1 : sub_ln1347_25_fu_1515_p2);

assign select_ln89_26_fu_1552_p3 = ((tmp_25_fu_714_p3[0:0] == 1'b1) ? rhs_0_26_fu_1542_p1 : sub_ln1347_26_fu_1546_p2);

assign select_ln89_27_fu_1872_p3 = ((tmp_26_reg_2611[0:0] == 1'b1) ? rhs_0_0_fu_725_p1 : sub_ln1347_fu_729_p2);

assign select_ln89_28_fu_1883_p3 = ((tmp_27_reg_2616[0:0] == 1'b1) ? rhs_0_1_fu_756_p1 : sub_ln1347_1_fu_760_p2);

assign select_ln89_29_fu_1894_p3 = ((tmp_28_reg_2621[0:0] == 1'b1) ? rhs_0_2_fu_787_p1 : sub_ln1347_2_fu_791_p2);

assign select_ln89_2_fu_797_p3 = ((tmp_1_reg_2546[0:0] == 1'b1) ? rhs_0_2_fu_787_p1 : sub_ln1347_2_fu_791_p2);

assign select_ln89_30_fu_1905_p3 = ((tmp_29_fu_1788_p3[0:0] == 1'b1) ? rhs_0_3_fu_818_p1 : sub_ln1347_3_fu_822_p2);

assign select_ln89_31_fu_1917_p3 = ((tmp_30_fu_1795_p3[0:0] == 1'b1) ? rhs_0_4_fu_850_p1 : sub_ln1347_4_fu_854_p2);

assign select_ln89_32_fu_1929_p3 = ((tmp_31_fu_1802_p3[0:0] == 1'b1) ? rhs_0_5_fu_882_p1 : sub_ln1347_5_fu_886_p2);

assign select_ln89_33_fu_1941_p3 = ((tmp_32_fu_1809_p3[0:0] == 1'b1) ? rhs_0_6_fu_914_p1 : sub_ln1347_6_fu_918_p2);

assign select_ln89_34_fu_1953_p3 = ((tmp_33_reg_2626[0:0] == 1'b1) ? rhs_0_7_fu_946_p1 : sub_ln1347_7_fu_950_p2);

assign select_ln89_35_fu_1964_p3 = ((tmp_34_reg_2631[0:0] == 1'b1) ? rhs_0_8_fu_977_p1 : sub_ln1347_8_fu_981_p2);

assign select_ln89_36_fu_1975_p3 = ((tmp_35_fu_1816_p3[0:0] == 1'b1) ? rhs_0_9_fu_1008_p1 : sub_ln1347_9_fu_1012_p2);

assign select_ln89_37_fu_1987_p3 = ((tmp_36_reg_2636[0:0] == 1'b1) ? rhs_0_10_fu_1040_p1 : sub_ln1347_10_fu_1044_p2);

assign select_ln89_38_fu_1998_p3 = ((tmp_37_fu_1823_p3[0:0] == 1'b1) ? rhs_0_11_fu_1071_p1 : sub_ln1347_11_fu_1075_p2);

assign select_ln89_39_fu_2010_p3 = ((tmp_38_fu_1830_p3[0:0] == 1'b1) ? rhs_0_12_fu_1103_p1 : sub_ln1347_12_fu_1107_p2);

assign select_ln89_3_fu_828_p3 = ((tmp_2_fu_637_p3[0:0] == 1'b1) ? rhs_0_3_fu_818_p1 : sub_ln1347_3_fu_822_p2);

assign select_ln89_40_fu_2022_p3 = ((tmp_39_reg_2641[0:0] == 1'b1) ? rhs_0_13_fu_1135_p1 : sub_ln1347_13_fu_1139_p2);

assign select_ln89_41_fu_2033_p3 = ((tmp_40_fu_1837_p3[0:0] == 1'b1) ? rhs_0_14_fu_1166_p1 : sub_ln1347_14_fu_1170_p2);

assign select_ln89_42_fu_2045_p3 = ((tmp_41_reg_2646[0:0] == 1'b1) ? rhs_0_15_fu_1198_p1 : sub_ln1347_15_fu_1202_p2);

assign select_ln89_43_fu_2056_p3 = ((tmp_42_fu_1844_p3[0:0] == 1'b1) ? rhs_0_16_fu_1229_p1 : sub_ln1347_16_fu_1233_p2);

assign select_ln89_44_fu_2068_p3 = ((tmp_43_fu_1851_p3[0:0] == 1'b1) ? rhs_0_17_fu_1261_p1 : sub_ln1347_17_fu_1265_p2);

assign select_ln89_45_fu_2080_p3 = ((tmp_44_fu_1858_p3[0:0] == 1'b1) ? rhs_0_18_fu_1293_p1 : sub_ln1347_18_fu_1297_p2);

assign select_ln89_46_fu_2092_p3 = ((tmp_45_reg_2651[0:0] == 1'b1) ? rhs_0_19_fu_1325_p1 : sub_ln1347_19_fu_1329_p2);

assign select_ln89_47_fu_2103_p3 = ((tmp_46_reg_2656[0:0] == 1'b1) ? rhs_0_20_fu_1356_p1 : sub_ln1347_20_fu_1360_p2);

assign select_ln89_48_fu_2114_p3 = ((tmp_47_reg_2661[0:0] == 1'b1) ? rhs_0_21_fu_1387_p1 : sub_ln1347_21_fu_1391_p2);

assign select_ln89_49_fu_2125_p3 = ((tmp_48_reg_2666[0:0] == 1'b1) ? rhs_0_22_fu_1418_p1 : sub_ln1347_22_fu_1422_p2);

assign select_ln89_4_fu_860_p3 = ((tmp_3_fu_644_p3[0:0] == 1'b1) ? rhs_0_4_fu_850_p1 : sub_ln1347_4_fu_854_p2);

assign select_ln89_50_fu_2136_p3 = ((tmp_49_reg_2671[0:0] == 1'b1) ? rhs_0_23_fu_1449_p1 : sub_ln1347_23_fu_1453_p2);

assign select_ln89_51_fu_2147_p3 = ((tmp_50_reg_2676[0:0] == 1'b1) ? rhs_0_24_fu_1480_p1 : sub_ln1347_24_fu_1484_p2);

assign select_ln89_52_fu_2158_p3 = ((tmp_51_reg_2681[0:0] == 1'b1) ? rhs_0_25_fu_1511_p1 : sub_ln1347_25_fu_1515_p2);

assign select_ln89_53_fu_2169_p3 = ((tmp_52_fu_1865_p3[0:0] == 1'b1) ? rhs_0_26_fu_1542_p1 : sub_ln1347_26_fu_1546_p2);

assign select_ln89_5_fu_892_p3 = ((tmp_4_fu_651_p3[0:0] == 1'b1) ? rhs_0_5_fu_882_p1 : sub_ln1347_5_fu_886_p2);

assign select_ln89_6_fu_924_p3 = ((tmp_5_fu_658_p3[0:0] == 1'b1) ? rhs_0_6_fu_914_p1 : sub_ln1347_6_fu_918_p2);

assign select_ln89_7_fu_956_p3 = ((tmp_6_reg_2551[0:0] == 1'b1) ? rhs_0_7_fu_946_p1 : sub_ln1347_7_fu_950_p2);

assign select_ln89_8_fu_987_p3 = ((tmp_7_reg_2556[0:0] == 1'b1) ? rhs_0_8_fu_977_p1 : sub_ln1347_8_fu_981_p2);

assign select_ln89_9_fu_1018_p3 = ((tmp_8_fu_665_p3[0:0] == 1'b1) ? rhs_0_9_fu_1008_p1 : sub_ln1347_9_fu_1012_p2);

assign select_ln89_fu_735_p3 = ((trunc_ln674_reg_2536[0:0] == 1'b1) ? rhs_0_0_fu_725_p1 : sub_ln1347_fu_729_p2);

assign sext_ln674_10_fu_1057_p1 = $signed(select_ln89_10_fu_1050_p3);

assign sext_ln674_11_fu_1089_p1 = $signed(select_ln89_11_fu_1081_p3);

assign sext_ln674_12_fu_1121_p1 = $signed(select_ln89_12_fu_1113_p3);

assign sext_ln674_13_fu_1152_p1 = $signed(select_ln89_13_fu_1145_p3);

assign sext_ln674_14_fu_1184_p1 = $signed(select_ln89_14_fu_1176_p3);

assign sext_ln674_15_fu_1215_p1 = $signed(select_ln89_15_fu_1208_p3);

assign sext_ln674_16_fu_1247_p1 = $signed(select_ln89_16_fu_1239_p3);

assign sext_ln674_17_fu_1279_p1 = $signed(select_ln89_17_fu_1271_p3);

assign sext_ln674_18_fu_1311_p1 = $signed(select_ln89_18_fu_1303_p3);

assign sext_ln674_19_fu_1342_p1 = $signed(select_ln89_19_fu_1335_p3);

assign sext_ln674_1_fu_773_p1 = $signed(select_ln89_1_fu_766_p3);

assign sext_ln674_20_fu_1373_p1 = $signed(select_ln89_20_fu_1366_p3);

assign sext_ln674_21_fu_1404_p1 = $signed(select_ln89_21_fu_1397_p3);

assign sext_ln674_22_fu_1435_p1 = $signed(select_ln89_22_fu_1428_p3);

assign sext_ln674_23_fu_1466_p1 = $signed(select_ln89_23_fu_1459_p3);

assign sext_ln674_24_fu_1497_p1 = $signed(select_ln89_24_fu_1490_p3);

assign sext_ln674_25_fu_1528_p1 = $signed(select_ln89_25_fu_1521_p3);

assign sext_ln674_2_fu_804_p1 = $signed(select_ln89_2_fu_797_p3);

assign sext_ln674_3_fu_836_p1 = $signed(select_ln89_3_fu_828_p3);

assign sext_ln674_4_fu_868_p1 = $signed(select_ln89_4_fu_860_p3);

assign sext_ln674_5_fu_900_p1 = $signed(select_ln89_5_fu_892_p3);

assign sext_ln674_6_fu_932_p1 = $signed(select_ln89_6_fu_924_p3);

assign sext_ln674_7_fu_963_p1 = $signed(select_ln89_7_fu_956_p3);

assign sext_ln674_8_fu_994_p1 = $signed(select_ln89_8_fu_987_p3);

assign sext_ln674_9_fu_1026_p1 = $signed(select_ln89_9_fu_1018_p3);

assign sext_ln674_fu_742_p1 = $signed(select_ln89_fu_735_p3);

assign sext_ln691_10_fu_1690_p1 = $signed(add_ln691_14_fu_1684_p2);

assign sext_ln691_11_fu_1700_p1 = $signed(add_ln691_15_fu_1694_p2);

assign sext_ln691_12_fu_1716_p1 = $signed(add_ln691_17_fu_1710_p2);

assign sext_ln691_13_fu_1732_p1 = $signed(add_ln691_19_fu_1726_p2);

assign sext_ln691_14_fu_1742_p1 = $signed(add_ln691_20_fu_1736_p2);

assign sext_ln691_15_fu_1752_p1 = $signed(add_ln691_21_fu_1746_p2);

assign sext_ln691_16_fu_1768_p1 = $signed(add_ln691_23_fu_1762_p2);

assign sext_ln691_17_fu_1778_p1 = $signed(add_ln691_24_fu_1772_p2);

assign sext_ln691_18_fu_2177_p1 = $signed(select_ln89_53_fu_2169_p3);

assign sext_ln691_19_fu_2193_p1 = $signed(add_ln691_27_fu_2187_p2);

assign sext_ln691_1_fu_1576_p1 = $signed(add_ln691_1_fu_1570_p2);

assign sext_ln691_20_fu_2209_p1 = $signed(add_ln691_29_fu_2203_p2);

assign sext_ln691_21_fu_2219_p1 = $signed(add_ln691_30_fu_2213_p2);

assign sext_ln691_22_fu_2235_p1 = $signed(add_ln691_32_fu_2229_p2);

assign sext_ln691_23_fu_2245_p1 = $signed(add_ln691_33_fu_2239_p2);

assign sext_ln691_24_fu_2255_p1 = $signed(add_ln691_34_fu_2249_p2);

assign sext_ln691_25_fu_2271_p1 = $signed(add_ln691_36_fu_2265_p2);

assign sext_ln691_26_fu_2281_p1 = $signed(add_ln691_37_fu_2275_p2);

assign sext_ln691_27_fu_2297_p1 = $signed(add_ln691_39_fu_2291_p2);

assign sext_ln691_28_fu_2307_p1 = $signed(add_ln691_40_fu_2301_p2);

assign sext_ln691_29_fu_2317_p1 = $signed(add_ln691_41_fu_2311_p2);

assign sext_ln691_2_fu_1592_p1 = $signed(add_ln691_3_fu_1586_p2);

assign sext_ln691_30_fu_2333_p1 = $signed(add_ln691_43_fu_2327_p2);

assign sext_ln691_31_fu_2349_p1 = $signed(add_ln691_45_fu_2343_p2);

assign sext_ln691_32_fu_2359_p1 = $signed(add_ln691_46_fu_2353_p2);

assign sext_ln691_33_fu_2369_p1 = $signed(add_ln691_47_fu_2363_p2);

assign sext_ln691_34_fu_2385_p1 = $signed(add_ln691_49_fu_2379_p2);

assign sext_ln691_35_fu_2395_p1 = $signed(add_ln691_50_fu_2389_p2);

assign sext_ln691_3_fu_1602_p1 = $signed(add_ln691_4_fu_1596_p2);

assign sext_ln691_4_fu_1618_p1 = $signed(add_ln691_6_fu_1612_p2);

assign sext_ln691_5_fu_1628_p1 = $signed(add_ln691_7_fu_1622_p2);

assign sext_ln691_6_fu_1638_p1 = $signed(add_ln691_8_fu_1632_p2);

assign sext_ln691_7_fu_1654_p1 = $signed(add_ln691_10_fu_1648_p2);

assign sext_ln691_8_fu_1664_p1 = $signed(add_ln691_11_fu_1658_p2);

assign sext_ln691_9_fu_1680_p1 = $signed(add_ln691_13_fu_1674_p2);

assign sext_ln691_fu_1560_p1 = $signed(select_ln89_26_fu_1552_p3);

assign sext_ln89_10_fu_1994_p1 = $signed(select_ln89_37_fu_1987_p3);

assign sext_ln89_11_fu_2006_p1 = $signed(select_ln89_38_fu_1998_p3);

assign sext_ln89_12_fu_2018_p1 = $signed(select_ln89_39_fu_2010_p3);

assign sext_ln89_13_fu_2029_p1 = $signed(select_ln89_40_fu_2022_p3);

assign sext_ln89_14_fu_2041_p1 = $signed(select_ln89_41_fu_2033_p3);

assign sext_ln89_15_fu_2052_p1 = $signed(select_ln89_42_fu_2045_p3);

assign sext_ln89_16_fu_2064_p1 = $signed(select_ln89_43_fu_2056_p3);

assign sext_ln89_17_fu_2076_p1 = $signed(select_ln89_44_fu_2068_p3);

assign sext_ln89_18_fu_2088_p1 = $signed(select_ln89_45_fu_2080_p3);

assign sext_ln89_19_fu_2099_p1 = $signed(select_ln89_46_fu_2092_p3);

assign sext_ln89_1_fu_1890_p1 = $signed(select_ln89_28_fu_1883_p3);

assign sext_ln89_20_fu_2110_p1 = $signed(select_ln89_47_fu_2103_p3);

assign sext_ln89_21_fu_2121_p1 = $signed(select_ln89_48_fu_2114_p3);

assign sext_ln89_22_fu_2132_p1 = $signed(select_ln89_49_fu_2125_p3);

assign sext_ln89_23_fu_2143_p1 = $signed(select_ln89_50_fu_2136_p3);

assign sext_ln89_24_fu_2154_p1 = $signed(select_ln89_51_fu_2147_p3);

assign sext_ln89_25_fu_2165_p1 = $signed(select_ln89_52_fu_2158_p3);

assign sext_ln89_2_fu_1901_p1 = $signed(select_ln89_29_fu_1894_p3);

assign sext_ln89_3_fu_1913_p1 = $signed(select_ln89_30_fu_1905_p3);

assign sext_ln89_4_fu_1925_p1 = $signed(select_ln89_31_fu_1917_p3);

assign sext_ln89_5_fu_1937_p1 = $signed(select_ln89_32_fu_1929_p3);

assign sext_ln89_6_fu_1949_p1 = $signed(select_ln89_33_fu_1941_p3);

assign sext_ln89_7_fu_1960_p1 = $signed(select_ln89_34_fu_1953_p3);

assign sext_ln89_8_fu_1971_p1 = $signed(select_ln89_35_fu_1964_p3);

assign sext_ln89_9_fu_1983_p1 = $signed(select_ln89_36_fu_1975_p3);

assign sext_ln89_fu_1879_p1 = $signed(select_ln89_27_fu_1872_p3);

assign sub_ln1347_10_fu_1044_p2 = ($signed(9'd0) - $signed(rhs_0_10_fu_1040_p1));

assign sub_ln1347_11_fu_1075_p2 = ($signed(9'd0) - $signed(rhs_0_11_fu_1071_p1));

assign sub_ln1347_12_fu_1107_p2 = ($signed(9'd0) - $signed(rhs_0_12_fu_1103_p1));

assign sub_ln1347_13_fu_1139_p2 = ($signed(9'd0) - $signed(rhs_0_13_fu_1135_p1));

assign sub_ln1347_14_fu_1170_p2 = ($signed(9'd0) - $signed(rhs_0_14_fu_1166_p1));

assign sub_ln1347_15_fu_1202_p2 = ($signed(9'd0) - $signed(rhs_0_15_fu_1198_p1));

assign sub_ln1347_16_fu_1233_p2 = ($signed(9'd0) - $signed(rhs_0_16_fu_1229_p1));

assign sub_ln1347_17_fu_1265_p2 = ($signed(9'd0) - $signed(rhs_0_17_fu_1261_p1));

assign sub_ln1347_18_fu_1297_p2 = ($signed(9'd0) - $signed(rhs_0_18_fu_1293_p1));

assign sub_ln1347_19_fu_1329_p2 = ($signed(9'd0) - $signed(rhs_0_19_fu_1325_p1));

assign sub_ln1347_1_fu_760_p2 = ($signed(9'd0) - $signed(rhs_0_1_fu_756_p1));

assign sub_ln1347_20_fu_1360_p2 = ($signed(9'd0) - $signed(rhs_0_20_fu_1356_p1));

assign sub_ln1347_21_fu_1391_p2 = ($signed(9'd0) - $signed(rhs_0_21_fu_1387_p1));

assign sub_ln1347_22_fu_1422_p2 = ($signed(9'd0) - $signed(rhs_0_22_fu_1418_p1));

assign sub_ln1347_23_fu_1453_p2 = ($signed(9'd0) - $signed(rhs_0_23_fu_1449_p1));

assign sub_ln1347_24_fu_1484_p2 = ($signed(9'd0) - $signed(rhs_0_24_fu_1480_p1));

assign sub_ln1347_25_fu_1515_p2 = ($signed(9'd0) - $signed(rhs_0_25_fu_1511_p1));

assign sub_ln1347_26_fu_1546_p2 = ($signed(9'd0) - $signed(rhs_0_26_fu_1542_p1));

assign sub_ln1347_2_fu_791_p2 = ($signed(9'd0) - $signed(rhs_0_2_fu_787_p1));

assign sub_ln1347_3_fu_822_p2 = ($signed(9'd0) - $signed(rhs_0_3_fu_818_p1));

assign sub_ln1347_4_fu_854_p2 = ($signed(9'd0) - $signed(rhs_0_4_fu_850_p1));

assign sub_ln1347_5_fu_886_p2 = ($signed(9'd0) - $signed(rhs_0_5_fu_882_p1));

assign sub_ln1347_6_fu_918_p2 = ($signed(9'd0) - $signed(rhs_0_6_fu_914_p1));

assign sub_ln1347_7_fu_950_p2 = ($signed(9'd0) - $signed(rhs_0_7_fu_946_p1));

assign sub_ln1347_8_fu_981_p2 = ($signed(9'd0) - $signed(rhs_0_8_fu_977_p1));

assign sub_ln1347_9_fu_1012_p2 = ($signed(9'd0) - $signed(rhs_0_9_fu_1008_p1));

assign sub_ln1347_fu_729_p2 = ($signed(9'd0) - $signed(rhs_0_0_fu_725_p1));

assign threshs_m_thresholds_V_0_0_address0 = idxprom2_i_fu_606_p1;

assign threshs_m_thresholds_V_0_1_address0 = idxprom2_i_fu_606_p1;

assign threshs_m_thresholds_V_1_0_address0 = idxprom2_i_fu_606_p1;

assign threshs_m_thresholds_V_1_1_address0 = idxprom2_i_fu_606_p1;

assign tmp_10_fu_672_p3 = weights_V_read_reg_2508[32'd11];

assign tmp_11_fu_679_p3 = weights_V_read_reg_2508[32'd12];

assign tmp_13_fu_686_p3 = weights_V_read_reg_2508[32'd14];

assign tmp_15_fu_693_p3 = weights_V_read_reg_2508[32'd16];

assign tmp_16_fu_700_p3 = weights_V_read_reg_2508[32'd17];

assign tmp_17_fu_707_p3 = weights_V_read_reg_2508[32'd18];

assign tmp_25_fu_714_p3 = weights_V_read_reg_2508[32'd26];

assign tmp_29_fu_1788_p3 = weights_V_read_reg_2508[32'd30];

assign tmp_2_fu_637_p3 = weights_V_read_reg_2508[32'd3];

assign tmp_30_fu_1795_p3 = weights_V_read_reg_2508[32'd31];

assign tmp_31_fu_1802_p3 = weights_V_read_reg_2508[32'd32];

assign tmp_32_fu_1809_p3 = weights_V_read_reg_2508[32'd33];

assign tmp_35_fu_1816_p3 = weights_V_read_reg_2508[32'd36];

assign tmp_37_fu_1823_p3 = weights_V_read_reg_2508[32'd38];

assign tmp_38_fu_1830_p3 = weights_V_read_reg_2508[32'd39];

assign tmp_3_fu_644_p3 = weights_V_read_reg_2508[32'd4];

assign tmp_40_fu_1837_p3 = weights_V_read_reg_2508[32'd41];

assign tmp_42_fu_1844_p3 = weights_V_read_reg_2508[32'd43];

assign tmp_43_fu_1851_p3 = weights_V_read_reg_2508[32'd44];

assign tmp_44_fu_1858_p3 = weights_V_read_reg_2508[32'd45];

assign tmp_4_fu_651_p3 = weights_V_read_reg_2508[32'd5];

assign tmp_52_fu_1865_p3 = weights_V_read_reg_2508[32'd53];

assign tmp_5_fu_658_p3 = weights_V_read_reg_2508[32'd6];

assign tmp_8_fu_665_p3 = weights_V_read_reg_2508[32'd9];

assign trunc_ln674_1_fu_721_p1 = p_Val2_s_fu_250[7:0];

assign trunc_ln674_fu_370_p1 = weights_V_TDATA[0:0];

assign xor_ln890_1_fu_2461_p2 = (icmp_ln890_1_fu_2455_p2 ^ 1'd1);

assign xor_ln890_fu_2425_p2 = (icmp_ln890_fu_2419_p2 ^ 1'd1);

assign zext_ln691_1_fu_2467_p1 = xor_ln890_1_fu_2461_p2;

assign zext_ln691_fu_2431_p1 = xor_ln890_fu_2425_p2;

endmodule //StreamingFCLayer_Batch_0_Matrix_Vector_Activate_Stream_Batch_27u_64u_27u_2u_Slice_ap_int_8u_Slice_ap_int_2_2u_Recast_Binary_ap_uint_1_ap_uint_216_ap_uint_4_ThresholdsActivation_32u_2u_2u_ap_int_13_ap_int_2_1_less_equal_ap_int_13_ap_resource_lut_s
