// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ConvolutionInputGenerator_1_ConvolutionInputGenerator_3u_64u_2u_130u_128u_4u_1u_ap_resource_lutram_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in0_V_TDATA,
        in0_V_TVALID,
        in0_V_TREADY,
        out_V_TDATA,
        out_V_TVALID,
        out_V_TREADY
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state4 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] in0_V_TDATA;
input   in0_V_TVALID;
output   in0_V_TREADY;
output  [7:0] out_V_TDATA;
output   out_V_TVALID;
input   out_V_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in0_V_TREADY;
reg out_V_TVALID;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    in0_V_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln197_fu_402_p2;
wire   [0:0] icmp_ln199_fu_418_p2;
wire   [0:0] icmp_ln215_fu_427_p2;
wire   [0:0] and_ln245_fu_804_p2;
reg    out_V_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter1;
reg   [0:0] icmp_ln199_reg_1043;
reg   [0:0] icmp_ln215_reg_1047;
reg   [21:0] i_reg_273;
wire   [21:0] i_1_fu_396_p2;
reg    ap_predicate_op126_read_state2;
reg    ap_predicate_op175_read_state2;
reg    ap_block_state2_pp0_stage0_iter0;
reg    ap_predicate_op217_write_state3;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_state3_io;
reg    ap_block_pp0_stage0_11001;
wire   [1:0] add_ln221_fu_504_p2;
reg   [1:0] add_ln221_reg_1054;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
wire   [11:0] inputBuf_V_0_address0;
reg    inputBuf_V_0_ce0;
wire   [7:0] inputBuf_V_0_q0;
reg   [11:0] inputBuf_V_0_address1;
reg    inputBuf_V_0_ce1;
reg    inputBuf_V_0_we1;
wire   [11:0] inputBuf_V_1_address0;
reg    inputBuf_V_1_ce0;
wire   [7:0] inputBuf_V_1_q0;
reg   [11:0] inputBuf_V_1_address1;
reg    inputBuf_V_1_ce1;
reg    inputBuf_V_1_we1;
wire   [11:0] inputBuf_V_2_address0;
reg    inputBuf_V_2_ce0;
wire   [7:0] inputBuf_V_2_q0;
reg   [11:0] inputBuf_V_2_address1;
reg    inputBuf_V_2_ce1;
reg    inputBuf_V_2_we1;
wire   [11:0] inputBuf_V_3_address0;
reg    inputBuf_V_3_ce0;
wire   [7:0] inputBuf_V_3_q0;
reg   [11:0] inputBuf_V_3_address1;
reg    inputBuf_V_3_ce1;
reg    inputBuf_V_3_we1;
wire   [63:0] zext_ln221_fu_490_p1;
wire   [63:0] zext_ln248_fu_810_p1;
wire   [63:0] zext_ln202_fu_879_p1;
reg   [31:0] current_block_write_fu_80;
wire   [31:0] current_block_write_4_fu_833_p3;
wire   [0:0] icmp_ln252_fu_339_p2;
wire   [31:0] current_block_write_2_fu_917_p3;
wire   [0:0] icmp_ln205_fu_345_p2;
reg   [31:0] read_block_fu_84;
wire   [31:0] read_block_2_fu_821_p2;
wire   [31:0] read_block_1_fu_925_p2;
reg   [31:0] ofm_y_fu_88;
wire   [31:0] ofm_y_6_fu_685_p3;
reg   [31:0] ofm_x_fu_92;
wire   [31:0] ofm_x_2_fu_718_p3;
reg   [31:0] k_y_fu_96;
wire   [31:0] k_y_2_fu_743_p3;
reg   [31:0] k_x_fu_100;
wire   [31:0] k_x_2_fu_768_p3;
reg   [31:0] count_simd_fu_104;
wire   [31:0] count_simd_2_fu_783_p3;
reg   [31:0] current_line_fu_108;
wire   [31:0] grp_fu_333_p2;
reg   [31:0] counter_internal_block_fu_112;
wire   [31:0] counter_internal_block_2_fu_866_p3;
reg   [31:0] inp_fu_116;
wire   [31:0] inp_5_fu_652_p3;
wire   [31:0] inp_6_fu_891_p2;
wire   [7:0] tmp_fu_941_p6;
reg    ap_block_pp0_stage0_01001;
wire   [1:0] trunc_ln216_fu_448_p1;
wire   [1:0] trunc_ln202_fu_887_p1;
wire   [7:0] trunc_ln220_1_fu_466_p1;
wire   [7:0] trunc_ln220_fu_462_p1;
wire   [7:0] add_ln220_fu_470_p2;
wire   [11:0] shl_ln_fu_476_p3;
wire   [11:0] trunc_ln197_fu_414_p1;
wire   [11:0] current_line_in_block_fu_484_p2;
wire   [1:0] trunc_ln216_1_fu_458_p1;
wire   [1:0] add_ln221_1_fu_498_p2;
wire   [31:0] count_simd_1_fu_510_p2;
wire   [31:0] k_x_1_fu_522_p2;
wire   [31:0] k_y_1_fu_534_p2;
wire   [31:0] ofm_x_1_fu_546_p2;
wire   [31:0] ofm_y_1_fu_558_p2;
wire   [0:0] icmp_ln236_fu_564_p2;
wire   [0:0] icmp_ln224_fu_516_p2;
wire   [0:0] icmp_ln227_fu_528_p2;
wire   [0:0] icmp_ln230_fu_540_p2;
wire   [0:0] icmp_ln233_fu_552_p2;
wire   [0:0] and_ln233_fu_592_p2;
wire   [0:0] and_ln227_fu_586_p2;
wire   [0:0] and_ln233_1_fu_598_p2;
wire   [31:0] inp_1_fu_570_p3;
wire   [31:0] inp_2_fu_604_p3;
wire   [0:0] xor_ln227_fu_620_p2;
wire   [0:0] and_ln227_1_fu_626_p2;
wire   [31:0] inp_3_fu_612_p3;
wire   [0:0] xor_ln230_fu_640_p2;
wire   [0:0] and_ln230_fu_646_p2;
wire   [31:0] inp_4_fu_632_p3;
wire   [31:0] ofm_y_2_fu_578_p3;
wire   [31:0] ofm_y_3_fu_661_p3;
wire   [31:0] ofm_y_4_fu_669_p3;
wire   [31:0] ofm_y_5_fu_677_p3;
wire   [31:0] select_ln233_fu_694_p3;
wire   [31:0] select_ln224_fu_702_p3;
wire   [31:0] select_ln227_fu_710_p3;
wire   [31:0] select_ln224_1_fu_727_p3;
wire   [31:0] select_ln227_1_fu_735_p3;
wire   [31:0] select_ln224_2_fu_752_p3;
wire   [31:0] select_ln227_2_fu_760_p3;
wire   [0:0] or_ln230_fu_777_p2;
wire   [0:0] icmp_ln245_fu_792_p2;
wire   [0:0] icmp_ln245_1_fu_798_p2;
wire   [31:0] current_block_write_3_fu_452_p2;
wire   [0:0] icmp_ln257_fu_827_p2;
wire   [31:0] counter_internal_block_1_fu_854_p2;
wire   [0:0] icmp_ln264_fu_860_p2;
wire   [31:0] current_block_write_1_fu_905_p2;
wire   [0:0] icmp_ln208_fu_911_p2;
wire    ap_CS_fsm_state4;
reg   [2:0] ap_NS_fsm;
reg    ap_block_pp0;
reg    ap_predicate_op133_store_state2;
reg    ap_enable_operation_133;
reg    ap_enable_state2_pp0_iter0_stage0;
reg    ap_predicate_op72_load_state2;
reg    ap_enable_operation_72;
reg    ap_predicate_op214_load_state3;
reg    ap_enable_operation_214;
reg    ap_enable_state3_pp0_iter1_stage0;
reg    ap_predicate_op183_store_state2;
reg    ap_enable_operation_183;
reg    ap_predicate_op135_store_state2;
reg    ap_enable_operation_135;
reg    ap_predicate_op70_load_state2;
reg    ap_enable_operation_70;
reg    ap_predicate_op213_load_state3;
reg    ap_enable_operation_213;
reg    ap_predicate_op185_store_state2;
reg    ap_enable_operation_185;
reg    ap_predicate_op137_store_state2;
reg    ap_enable_operation_137;
reg    ap_predicate_op68_load_state2;
reg    ap_enable_operation_68;
reg    ap_predicate_op212_load_state3;
reg    ap_enable_operation_212;
reg    ap_predicate_op187_store_state2;
reg    ap_enable_operation_187;
reg    ap_predicate_op139_store_state2;
reg    ap_enable_operation_139;
reg    ap_predicate_op74_load_state2;
reg    ap_enable_operation_74;
reg    ap_predicate_op215_load_state3;
reg    ap_enable_operation_215;
reg    ap_predicate_op189_store_state2;
reg    ap_enable_operation_189;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_736;
reg    ap_condition_245;
reg    ap_condition_742;
reg    ap_condition_746;
reg    ap_condition_750;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

ConvolutionInputGenerator_1_ConvolutionInputGenerator_3u_64u_2u_130u_128u_4u_1u_ap_resource_lutram_s_inpubkb #(
    .DataWidth( 8 ),
    .AddressRange( 2080 ),
    .AddressWidth( 12 ))
inputBuf_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_V_0_address0),
    .ce0(inputBuf_V_0_ce0),
    .q0(inputBuf_V_0_q0),
    .address1(inputBuf_V_0_address1),
    .ce1(inputBuf_V_0_ce1),
    .we1(inputBuf_V_0_we1),
    .d1(in0_V_TDATA)
);

ConvolutionInputGenerator_1_ConvolutionInputGenerator_3u_64u_2u_130u_128u_4u_1u_ap_resource_lutram_s_inpubkb #(
    .DataWidth( 8 ),
    .AddressRange( 2080 ),
    .AddressWidth( 12 ))
inputBuf_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_V_1_address0),
    .ce0(inputBuf_V_1_ce0),
    .q0(inputBuf_V_1_q0),
    .address1(inputBuf_V_1_address1),
    .ce1(inputBuf_V_1_ce1),
    .we1(inputBuf_V_1_we1),
    .d1(in0_V_TDATA)
);

ConvolutionInputGenerator_1_ConvolutionInputGenerator_3u_64u_2u_130u_128u_4u_1u_ap_resource_lutram_s_inpubkb #(
    .DataWidth( 8 ),
    .AddressRange( 2080 ),
    .AddressWidth( 12 ))
inputBuf_V_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_V_2_address0),
    .ce0(inputBuf_V_2_ce0),
    .q0(inputBuf_V_2_q0),
    .address1(inputBuf_V_2_address1),
    .ce1(inputBuf_V_2_ce1),
    .we1(inputBuf_V_2_we1),
    .d1(in0_V_TDATA)
);

ConvolutionInputGenerator_1_ConvolutionInputGenerator_3u_64u_2u_130u_128u_4u_1u_ap_resource_lutram_s_inpubkb #(
    .DataWidth( 8 ),
    .AddressRange( 2080 ),
    .AddressWidth( 12 ))
inputBuf_V_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(inputBuf_V_3_address0),
    .ce0(inputBuf_V_3_ce0),
    .q0(inputBuf_V_3_q0),
    .address1(inputBuf_V_3_address1),
    .ce1(inputBuf_V_3_ce1),
    .we1(inputBuf_V_3_we1),
    .d1(in0_V_TDATA)
);

ConvolutionInputGenerator_1_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_42_8_1_1_U1(
    .din0(inputBuf_V_0_q0),
    .din1(inputBuf_V_1_q0),
    .din2(inputBuf_V_2_q0),
    .din3(inputBuf_V_3_q0),
    .din4(add_ln221_reg_1054),
    .dout(tmp_fu_941_p6)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        count_simd_fu_104 <= 32'd0;
    end else if ((((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln252_fu_339_p2 == 1'd0)) | ((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln252_fu_339_p2 == 1'd1)) | ((icmp_ln215_fu_427_p2 == 1'd1) & (icmp_ln199_fu_418_p2 == 1'd0) & (1'd0 == and_ln245_fu_804_p2) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        count_simd_fu_104 <= count_simd_2_fu_783_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln199_fu_418_p2 == 1'd1) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln205_fu_345_p2 == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        counter_internal_block_fu_112 <= 32'd0;
    end else if (((icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        counter_internal_block_fu_112 <= counter_internal_block_2_fu_866_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        current_block_write_fu_80 <= 32'd0;
    end else if (((icmp_ln199_fu_418_p2 == 1'd1) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln205_fu_345_p2 == 1'd1))) begin
        current_block_write_fu_80 <= current_block_write_2_fu_917_p3;
    end else if (((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln252_fu_339_p2 == 1'd1))) begin
        current_block_write_fu_80 <= current_block_write_4_fu_833_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln252_fu_339_p2 == 1'd1)) | ((icmp_ln199_fu_418_p2 == 1'd1) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln205_fu_345_p2 == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        current_line_fu_108 <= 32'd0;
    end else if ((((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln252_fu_339_p2 == 1'd0)) | ((icmp_ln199_fu_418_p2 == 1'd1) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln205_fu_345_p2 == 1'd0)))) begin
        current_line_fu_108 <= grp_fu_333_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_reg_273 <= i_1_fu_396_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_273 <= 22'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        inp_fu_116 <= 32'd0;
    end else if (((icmp_ln199_fu_418_p2 == 1'd1) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inp_fu_116 <= inp_6_fu_891_p2;
    end else if ((((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln252_fu_339_p2 == 1'd0)) | ((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln252_fu_339_p2 == 1'd1)) | ((icmp_ln215_fu_427_p2 == 1'd1) & (icmp_ln199_fu_418_p2 == 1'd0) & (1'd0 == and_ln245_fu_804_p2) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inp_fu_116 <= inp_5_fu_652_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        k_x_fu_100 <= 32'd0;
    end else if ((((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln252_fu_339_p2 == 1'd0)) | ((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln252_fu_339_p2 == 1'd1)) | ((icmp_ln215_fu_427_p2 == 1'd1) & (icmp_ln199_fu_418_p2 == 1'd0) & (1'd0 == and_ln245_fu_804_p2) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        k_x_fu_100 <= k_x_2_fu_768_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        k_y_fu_96 <= 32'd0;
    end else if ((((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln252_fu_339_p2 == 1'd0)) | ((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln252_fu_339_p2 == 1'd1)) | ((icmp_ln215_fu_427_p2 == 1'd1) & (icmp_ln199_fu_418_p2 == 1'd0) & (1'd0 == and_ln245_fu_804_p2) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        k_y_fu_96 <= k_y_2_fu_743_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ofm_x_fu_92 <= 32'd0;
    end else if ((((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln252_fu_339_p2 == 1'd0)) | ((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln252_fu_339_p2 == 1'd1)) | ((icmp_ln215_fu_427_p2 == 1'd1) & (icmp_ln199_fu_418_p2 == 1'd0) & (1'd0 == and_ln245_fu_804_p2) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        ofm_x_fu_92 <= ofm_x_2_fu_718_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ofm_y_fu_88 <= 32'd0;
    end else if ((((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln252_fu_339_p2 == 1'd0)) | ((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln252_fu_339_p2 == 1'd1)) | ((icmp_ln215_fu_427_p2 == 1'd1) & (icmp_ln199_fu_418_p2 == 1'd0) & (1'd0 == and_ln245_fu_804_p2) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        ofm_y_fu_88 <= ofm_y_6_fu_685_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        read_block_fu_84 <= 32'd0;
    end else if (((icmp_ln199_fu_418_p2 == 1'd1) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln205_fu_345_p2 == 1'd1))) begin
        read_block_fu_84 <= read_block_1_fu_925_p2;
    end else if (((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln252_fu_339_p2 == 1'd1))) begin
        read_block_fu_84 <= read_block_2_fu_821_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln215_fu_427_p2 == 1'd1) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln221_reg_1054 <= add_ln221_fu_504_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln199_reg_1043 <= icmp_ln199_fu_418_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln215_reg_1047 <= icmp_ln215_fu_427_p2;
    end
end

always @ (*) begin
    if ((icmp_ln197_fu_402_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln199_fu_418_p2 == 1'd1) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_predicate_op175_read_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_predicate_op126_read_state2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        in0_V_TREADY = 1'b1;
    end else begin
        in0_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_245)) begin
        if (((icmp_ln199_fu_418_p2 == 1'd1) & (trunc_ln202_fu_887_p1 == 2'd0))) begin
            inputBuf_V_0_address1 = zext_ln202_fu_879_p1;
        end else if ((1'b1 == ap_condition_736)) begin
            inputBuf_V_0_address1 = zext_ln248_fu_810_p1;
        end else begin
            inputBuf_V_0_address1 = 'bx;
        end
    end else begin
        inputBuf_V_0_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inputBuf_V_0_ce0 = 1'b1;
    end else begin
        inputBuf_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (trunc_ln216_fu_448_p1 == 2'd0) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln199_fu_418_p2 == 1'd1) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (trunc_ln202_fu_887_p1 == 2'd0) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputBuf_V_0_ce1 = 1'b1;
    end else begin
        inputBuf_V_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (trunc_ln216_fu_448_p1 == 2'd0) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln199_fu_418_p2 == 1'd1) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (trunc_ln202_fu_887_p1 == 2'd0) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputBuf_V_0_we1 = 1'b1;
    end else begin
        inputBuf_V_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_245)) begin
        if (((icmp_ln199_fu_418_p2 == 1'd1) & (trunc_ln202_fu_887_p1 == 2'd1))) begin
            inputBuf_V_1_address1 = zext_ln202_fu_879_p1;
        end else if ((1'b1 == ap_condition_742)) begin
            inputBuf_V_1_address1 = zext_ln248_fu_810_p1;
        end else begin
            inputBuf_V_1_address1 = 'bx;
        end
    end else begin
        inputBuf_V_1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inputBuf_V_1_ce0 = 1'b1;
    end else begin
        inputBuf_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (trunc_ln216_fu_448_p1 == 2'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln199_fu_418_p2 == 1'd1) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (trunc_ln202_fu_887_p1 == 2'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputBuf_V_1_ce1 = 1'b1;
    end else begin
        inputBuf_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (trunc_ln216_fu_448_p1 == 2'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln199_fu_418_p2 == 1'd1) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (trunc_ln202_fu_887_p1 == 2'd1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputBuf_V_1_we1 = 1'b1;
    end else begin
        inputBuf_V_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_245)) begin
        if (((icmp_ln199_fu_418_p2 == 1'd1) & (trunc_ln202_fu_887_p1 == 2'd2))) begin
            inputBuf_V_2_address1 = zext_ln202_fu_879_p1;
        end else if ((1'b1 == ap_condition_746)) begin
            inputBuf_V_2_address1 = zext_ln248_fu_810_p1;
        end else begin
            inputBuf_V_2_address1 = 'bx;
        end
    end else begin
        inputBuf_V_2_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inputBuf_V_2_ce0 = 1'b1;
    end else begin
        inputBuf_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (trunc_ln216_fu_448_p1 == 2'd2) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln199_fu_418_p2 == 1'd1) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (trunc_ln202_fu_887_p1 == 2'd2) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputBuf_V_2_ce1 = 1'b1;
    end else begin
        inputBuf_V_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (trunc_ln216_fu_448_p1 == 2'd2) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln199_fu_418_p2 == 1'd1) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (trunc_ln202_fu_887_p1 == 2'd2) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputBuf_V_2_we1 = 1'b1;
    end else begin
        inputBuf_V_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_245)) begin
        if (((icmp_ln199_fu_418_p2 == 1'd1) & (trunc_ln202_fu_887_p1 == 2'd3))) begin
            inputBuf_V_3_address1 = zext_ln202_fu_879_p1;
        end else if ((1'b1 == ap_condition_750)) begin
            inputBuf_V_3_address1 = zext_ln248_fu_810_p1;
        end else begin
            inputBuf_V_3_address1 = 'bx;
        end
    end else begin
        inputBuf_V_3_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        inputBuf_V_3_ce0 = 1'b1;
    end else begin
        inputBuf_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (trunc_ln216_fu_448_p1 == 2'd3) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln199_fu_418_p2 == 1'd1) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (trunc_ln202_fu_887_p1 == 2'd3) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputBuf_V_3_ce1 = 1'b1;
    end else begin
        inputBuf_V_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (trunc_ln216_fu_448_p1 == 2'd3) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln199_fu_418_p2 == 1'd1) & (icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (trunc_ln202_fu_887_p1 == 2'd3) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputBuf_V_3_we1 = 1'b1;
    end else begin
        inputBuf_V_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln215_reg_1047 == 1'd1) & (icmp_ln199_reg_1043 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_V_TDATA_blk_n = out_V_TREADY;
    end else begin
        out_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_predicate_op217_write_state3 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_V_TVALID = 1'b1;
    end else begin
        out_V_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((icmp_ln197_fu_402_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((icmp_ln197_fu_402_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln220_fu_470_p2 = (trunc_ln220_1_fu_466_p1 + trunc_ln220_fu_462_p1);

assign add_ln221_1_fu_498_p2 = (trunc_ln216_1_fu_458_p1 + 2'd1);

assign add_ln221_fu_504_p2 = (add_ln221_1_fu_498_p2 + trunc_ln216_fu_448_p1);

assign and_ln227_1_fu_626_p2 = (xor_ln227_fu_620_p2 & icmp_ln224_fu_516_p2);

assign and_ln227_fu_586_p2 = (icmp_ln227_fu_528_p2 & icmp_ln224_fu_516_p2);

assign and_ln230_fu_646_p2 = (xor_ln230_fu_640_p2 & and_ln227_fu_586_p2);

assign and_ln233_1_fu_598_p2 = (and_ln233_fu_592_p2 & and_ln227_fu_586_p2);

assign and_ln233_fu_592_p2 = (icmp_ln233_fu_552_p2 & icmp_ln230_fu_540_p2);

assign and_ln245_fu_804_p2 = (icmp_ln245_fu_792_p2 & icmp_ln245_1_fu_798_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_predicate_op217_write_state3 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (out_V_TREADY == 1'b0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (((ap_predicate_op175_read_state2 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op126_read_state2 == 1'b1) & (in0_V_TVALID == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op217_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (((ap_predicate_op175_read_state2 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op126_read_state2 == 1'b1) & (in0_V_TVALID == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & ((1'b1 == ap_block_state3_io) | ((ap_predicate_op217_write_state3 == 1'b1) & (out_V_TREADY == 1'b0)))) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (((ap_predicate_op175_read_state2 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op126_read_state2 == 1'b1) & (in0_V_TVALID == 1'b0)))));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = (((ap_predicate_op175_read_state2 == 1'b1) & (in0_V_TVALID == 1'b0)) | ((ap_predicate_op126_read_state2 == 1'b1) & (in0_V_TVALID == 1'b0)));
end

always @ (*) begin
    ap_block_state3_io = ((ap_predicate_op217_write_state3 == 1'b1) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((ap_predicate_op217_write_state3 == 1'b1) & (out_V_TREADY == 1'b0));
end

always @ (*) begin
    ap_condition_245 = ((icmp_ln197_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_736 = ((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (trunc_ln216_fu_448_p1 == 2'd0));
end

always @ (*) begin
    ap_condition_742 = ((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (trunc_ln216_fu_448_p1 == 2'd1));
end

always @ (*) begin
    ap_condition_746 = ((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (trunc_ln216_fu_448_p1 == 2'd2));
end

always @ (*) begin
    ap_condition_750 = ((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (trunc_ln216_fu_448_p1 == 2'd3));
end

always @ (*) begin
    ap_enable_operation_133 = (ap_predicate_op133_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_135 = (ap_predicate_op135_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_137 = (ap_predicate_op137_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_139 = (ap_predicate_op139_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_183 = (ap_predicate_op183_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_185 = (ap_predicate_op185_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_187 = (ap_predicate_op187_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_189 = (ap_predicate_op189_store_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_212 = (ap_predicate_op212_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_213 = (ap_predicate_op213_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_214 = (ap_predicate_op214_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_215 = (ap_predicate_op215_load_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_68 = (ap_predicate_op68_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_70 = (ap_predicate_op70_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_72 = (ap_predicate_op72_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_74 = (ap_predicate_op74_load_state2 == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_enable_state2_pp0_iter0_stage0 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state3_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_predicate_op126_read_state2 = ((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op133_store_state2 = ((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0) & (trunc_ln216_fu_448_p1 == 2'd2));
end

always @ (*) begin
    ap_predicate_op135_store_state2 = ((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0) & (trunc_ln216_fu_448_p1 == 2'd1));
end

always @ (*) begin
    ap_predicate_op137_store_state2 = ((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0) & (trunc_ln216_fu_448_p1 == 2'd0));
end

always @ (*) begin
    ap_predicate_op139_store_state2 = ((icmp_ln215_fu_427_p2 == 1'd1) & (1'd1 == and_ln245_fu_804_p2) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0) & (trunc_ln216_fu_448_p1 == 2'd3));
end

always @ (*) begin
    ap_predicate_op175_read_state2 = ((icmp_ln199_fu_418_p2 == 1'd1) & (icmp_ln197_fu_402_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op183_store_state2 = ((icmp_ln199_fu_418_p2 == 1'd1) & (icmp_ln197_fu_402_p2 == 1'd0) & (trunc_ln202_fu_887_p1 == 2'd2));
end

always @ (*) begin
    ap_predicate_op185_store_state2 = ((icmp_ln199_fu_418_p2 == 1'd1) & (icmp_ln197_fu_402_p2 == 1'd0) & (trunc_ln202_fu_887_p1 == 2'd1));
end

always @ (*) begin
    ap_predicate_op187_store_state2 = ((icmp_ln199_fu_418_p2 == 1'd1) & (icmp_ln197_fu_402_p2 == 1'd0) & (trunc_ln202_fu_887_p1 == 2'd0));
end

always @ (*) begin
    ap_predicate_op189_store_state2 = ((icmp_ln199_fu_418_p2 == 1'd1) & (icmp_ln197_fu_402_p2 == 1'd0) & (trunc_ln202_fu_887_p1 == 2'd3));
end

always @ (*) begin
    ap_predicate_op212_load_state3 = ((icmp_ln215_reg_1047 == 1'd1) & (icmp_ln199_reg_1043 == 1'd0));
end

always @ (*) begin
    ap_predicate_op213_load_state3 = ((icmp_ln215_reg_1047 == 1'd1) & (icmp_ln199_reg_1043 == 1'd0));
end

always @ (*) begin
    ap_predicate_op214_load_state3 = ((icmp_ln215_reg_1047 == 1'd1) & (icmp_ln199_reg_1043 == 1'd0));
end

always @ (*) begin
    ap_predicate_op215_load_state3 = ((icmp_ln215_reg_1047 == 1'd1) & (icmp_ln199_reg_1043 == 1'd0));
end

always @ (*) begin
    ap_predicate_op217_write_state3 = ((icmp_ln215_reg_1047 == 1'd1) & (icmp_ln199_reg_1043 == 1'd0));
end

always @ (*) begin
    ap_predicate_op68_load_state2 = ((icmp_ln215_fu_427_p2 == 1'd1) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op70_load_state2 = ((icmp_ln215_fu_427_p2 == 1'd1) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op72_load_state2 = ((icmp_ln215_fu_427_p2 == 1'd1) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0));
end

always @ (*) begin
    ap_predicate_op74_load_state2 = ((icmp_ln215_fu_427_p2 == 1'd1) & (icmp_ln199_fu_418_p2 == 1'd0) & (icmp_ln197_fu_402_p2 == 1'd0));
end

assign count_simd_1_fu_510_p2 = (count_simd_fu_104 + 32'd1);

assign count_simd_2_fu_783_p3 = ((or_ln230_fu_777_p2[0:0] == 1'b1) ? 32'd0 : count_simd_1_fu_510_p2);

assign counter_internal_block_1_fu_854_p2 = (counter_internal_block_fu_112 + 32'd1);

assign counter_internal_block_2_fu_866_p3 = ((icmp_ln264_fu_860_p2[0:0] == 1'b1) ? 32'd0 : counter_internal_block_1_fu_854_p2);

assign current_block_write_1_fu_905_p2 = (current_block_write_fu_80 + 32'd1);

assign current_block_write_2_fu_917_p3 = ((icmp_ln208_fu_911_p2[0:0] == 1'b1) ? 32'd0 : current_block_write_1_fu_905_p2);

assign current_block_write_3_fu_452_p2 = (current_block_write_fu_80 + 32'd1);

assign current_block_write_4_fu_833_p3 = ((icmp_ln257_fu_827_p2[0:0] == 1'b1) ? 32'd0 : current_block_write_3_fu_452_p2);

assign current_line_in_block_fu_484_p2 = (shl_ln_fu_476_p3 + trunc_ln197_fu_414_p1);

assign grp_fu_333_p2 = (current_line_fu_108 + 32'd1);

assign i_1_fu_396_p2 = (i_reg_273 + 22'd1);

assign icmp_ln197_fu_402_p2 = ((i_reg_273 == 22'd2365536) ? 1'b1 : 1'b0);

assign icmp_ln199_fu_418_p2 = ((inp_fu_116 < 32'd6240) ? 1'b1 : 1'b0);

assign icmp_ln205_fu_345_p2 = ((grp_fu_333_p2 == 32'd2080) ? 1'b1 : 1'b0);

assign icmp_ln208_fu_911_p2 = ((current_block_write_1_fu_905_p2 == 32'd4) ? 1'b1 : 1'b0);

assign icmp_ln215_fu_427_p2 = ((counter_internal_block_fu_112 < 32'd18431) ? 1'b1 : 1'b0);

assign icmp_ln224_fu_516_p2 = ((count_simd_1_fu_510_p2 == 32'd16) ? 1'b1 : 1'b0);

assign icmp_ln227_fu_528_p2 = ((k_x_1_fu_522_p2 == 32'd3) ? 1'b1 : 1'b0);

assign icmp_ln230_fu_540_p2 = ((k_y_1_fu_534_p2 == 32'd3) ? 1'b1 : 1'b0);

assign icmp_ln233_fu_552_p2 = ((ofm_x_1_fu_546_p2 == 32'd128) ? 1'b1 : 1'b0);

assign icmp_ln236_fu_564_p2 = ((ofm_y_1_fu_558_p2 == 32'd128) ? 1'b1 : 1'b0);

assign icmp_ln245_1_fu_798_p2 = ((read_block_fu_84 < 32'd130) ? 1'b1 : 1'b0);

assign icmp_ln245_fu_792_p2 = ((counter_internal_block_fu_112 < 32'd2079) ? 1'b1 : 1'b0);

assign icmp_ln252_fu_339_p2 = ((grp_fu_333_p2 == 32'd2080) ? 1'b1 : 1'b0);

assign icmp_ln257_fu_827_p2 = ((current_block_write_3_fu_452_p2 == 32'd4) ? 1'b1 : 1'b0);

assign icmp_ln264_fu_860_p2 = ((counter_internal_block_1_fu_854_p2 == 32'd18431) ? 1'b1 : 1'b0);

assign inp_1_fu_570_p3 = ((icmp_ln236_fu_564_p2[0:0] == 1'b1) ? 32'd0 : inp_fu_116);

assign inp_2_fu_604_p3 = ((and_ln233_1_fu_598_p2[0:0] == 1'b1) ? inp_1_fu_570_p3 : inp_fu_116);

assign inp_3_fu_612_p3 = ((icmp_ln224_fu_516_p2[0:0] == 1'b1) ? inp_2_fu_604_p3 : inp_fu_116);

assign inp_4_fu_632_p3 = ((and_ln227_1_fu_626_p2[0:0] == 1'b1) ? inp_fu_116 : inp_3_fu_612_p3);

assign inp_5_fu_652_p3 = ((and_ln230_fu_646_p2[0:0] == 1'b1) ? inp_fu_116 : inp_4_fu_632_p3);

assign inp_6_fu_891_p2 = (inp_fu_116 + 32'd1);

assign inputBuf_V_0_address0 = zext_ln221_fu_490_p1;

assign inputBuf_V_1_address0 = zext_ln221_fu_490_p1;

assign inputBuf_V_2_address0 = zext_ln221_fu_490_p1;

assign inputBuf_V_3_address0 = zext_ln221_fu_490_p1;

assign k_x_1_fu_522_p2 = (k_x_fu_100 + 32'd1);

assign k_x_2_fu_768_p3 = ((and_ln230_fu_646_p2[0:0] == 1'b1) ? 32'd0 : select_ln227_2_fu_760_p3);

assign k_y_1_fu_534_p2 = (k_y_fu_96 + 32'd1);

assign k_y_2_fu_743_p3 = ((and_ln230_fu_646_p2[0:0] == 1'b1) ? k_y_1_fu_534_p2 : select_ln227_1_fu_735_p3);

assign ofm_x_1_fu_546_p2 = (ofm_x_fu_92 + 32'd1);

assign ofm_x_2_fu_718_p3 = ((and_ln230_fu_646_p2[0:0] == 1'b1) ? ofm_x_fu_92 : select_ln227_fu_710_p3);

assign ofm_y_1_fu_558_p2 = (ofm_y_fu_88 + 32'd1);

assign ofm_y_2_fu_578_p3 = ((icmp_ln236_fu_564_p2[0:0] == 1'b1) ? 32'd0 : ofm_y_1_fu_558_p2);

assign ofm_y_3_fu_661_p3 = ((and_ln233_1_fu_598_p2[0:0] == 1'b1) ? ofm_y_2_fu_578_p3 : ofm_y_fu_88);

assign ofm_y_4_fu_669_p3 = ((icmp_ln224_fu_516_p2[0:0] == 1'b1) ? ofm_y_3_fu_661_p3 : ofm_y_fu_88);

assign ofm_y_5_fu_677_p3 = ((and_ln227_1_fu_626_p2[0:0] == 1'b1) ? ofm_y_fu_88 : ofm_y_4_fu_669_p3);

assign ofm_y_6_fu_685_p3 = ((and_ln230_fu_646_p2[0:0] == 1'b1) ? ofm_y_fu_88 : ofm_y_5_fu_677_p3);

assign or_ln230_fu_777_p2 = (icmp_ln224_fu_516_p2 | and_ln230_fu_646_p2);

assign out_V_TDATA = tmp_fu_941_p6;

assign read_block_1_fu_925_p2 = (read_block_fu_84 + 32'd1);

assign read_block_2_fu_821_p2 = (read_block_fu_84 + 32'd1);

assign select_ln224_1_fu_727_p3 = ((icmp_ln224_fu_516_p2[0:0] == 1'b1) ? 32'd0 : k_y_fu_96);

assign select_ln224_2_fu_752_p3 = ((icmp_ln224_fu_516_p2[0:0] == 1'b1) ? 32'd0 : k_x_fu_100);

assign select_ln224_fu_702_p3 = ((icmp_ln224_fu_516_p2[0:0] == 1'b1) ? select_ln233_fu_694_p3 : ofm_x_fu_92);

assign select_ln227_1_fu_735_p3 = ((and_ln227_1_fu_626_p2[0:0] == 1'b1) ? k_y_fu_96 : select_ln224_1_fu_727_p3);

assign select_ln227_2_fu_760_p3 = ((and_ln227_1_fu_626_p2[0:0] == 1'b1) ? k_x_1_fu_522_p2 : select_ln224_2_fu_752_p3);

assign select_ln227_fu_710_p3 = ((and_ln227_1_fu_626_p2[0:0] == 1'b1) ? ofm_x_fu_92 : select_ln224_fu_702_p3);

assign select_ln233_fu_694_p3 = ((and_ln233_1_fu_598_p2[0:0] == 1'b1) ? 32'd0 : ofm_x_1_fu_546_p2);

assign shl_ln_fu_476_p3 = {{add_ln220_fu_470_p2}, {4'd0}};

assign trunc_ln197_fu_414_p1 = count_simd_fu_104[11:0];

assign trunc_ln202_fu_887_p1 = current_block_write_fu_80[1:0];

assign trunc_ln216_1_fu_458_p1 = k_y_fu_96[1:0];

assign trunc_ln216_fu_448_p1 = current_block_write_fu_80[1:0];

assign trunc_ln220_1_fu_466_p1 = ofm_x_fu_92[7:0];

assign trunc_ln220_fu_462_p1 = k_x_fu_100[7:0];

assign xor_ln227_fu_620_p2 = (icmp_ln227_fu_528_p2 ^ 1'd1);

assign xor_ln230_fu_640_p2 = (icmp_ln230_fu_540_p2 ^ 1'd1);

assign zext_ln202_fu_879_p1 = current_line_fu_108;

assign zext_ln221_fu_490_p1 = current_line_in_block_fu_484_p2;

assign zext_ln248_fu_810_p1 = current_line_fu_108;

endmodule //ConvolutionInputGenerator_1_ConvolutionInputGenerator_3u_64u_2u_130u_128u_4u_1u_ap_resource_lutram_s
